# generated by datamodel-codegen:
#   filename:  action-configs.json
#   timestamp: 2026-02-04T16:19:28+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class BaseActionConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    image: str | None = None
    """
    Base64 encoded reference image
    """


class ClickType(StrEnum):
    """
    Type of click to perform
    """

    left = 'left'
    right = 'right'


class ClickConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for element to click
    """
    waitTime: int | None = 1000
    """
    Wait time in milliseconds
    """
    forceClick: bool | None = False
    """
    Force click even if element not clickable
    """
    scrollIntoView: bool | None = True
    """
    Scroll element into view before clicking
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    clickType: ClickType | None = 'left'
    """
    Type of click to perform
    """
    clickCount: Annotated[int | None, Field(ge=1)] = 1
    """
    Number of clicks to perform
    """
    clickAndHold: bool | None = False
    """
    Whether to click and hold
    """
    holdDuration: int | None = 1000
    """
    Duration to hold click in milliseconds
    """


class InputConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for input element
    """
    text: str
    """
    Text to input
    """
    clearFirst: bool | None = True
    """
    Clear field before typing
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    scrollIntoView: bool | None = True
    """
    Scroll element into view
    """


class NavigateConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    url: AnyUrl
    """
    URL to navigate to
    """
    waitForLoad: bool | None = True
    """
    Wait for page to load
    """
    takeScreenshot: bool | None = False
    """
    Take screenshot after navigation
    """


class WaitType(StrEnum):
    """
    Type of wait to perform
    """

    duration = 'duration'
    element = 'element'
    interactable = 'interactable'


class WaitConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    waitType: WaitType | None = 'duration'
    """
    Type of wait to perform
    """
    duration: int | None = 3000
    """
    Duration to wait in milliseconds
    """
    selector: str | None = None
    """
    CSS selector for element to wait for
    """
    timeout: int | None = 10000
    """
    Maximum time to wait in milliseconds
    """
    waitForInteractable: bool | None = False
    """
    Wait for element to be interactable
    """
    fallbackToDuration: bool | None = True
    """
    Fallback to duration wait if element wait fails
    """
    fallbackDuration: int | None = 2000
    """
    Duration to wait if fallback triggered
    """


class AssertType(StrEnum):
    """
    Type of assertion
    """

    exists = 'exists'
    visible = 'visible'
    text = 'text'
    value = 'value'
    attribute = 'attribute'


class AssertionConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for element
    """
    assertType: AssertType | None = 'exists'
    """
    Type of assertion
    """
    expectedValue: str
    """
    Expected value for assertion
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    caseSensitive: bool | None = False
    """
    Case sensitive comparison
    """
    partialMatch: bool | None = False
    """
    Allow partial text matching
    """


class ScreenshotType(StrEnum):
    """
    Type of screenshot to capture
    """

    viewport = 'viewport'
    fullPage = 'fullPage'
    element = 'element'


class Format(StrEnum):
    """
    Output format
    """

    png = 'png'
    jpg = 'jpg'


class ScreenshotConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    screenshotType: ScreenshotType | None = 'viewport'
    """
    Type of screenshot to capture
    """
    selector: str | None = None
    """
    CSS selector for element screenshots
    """
    filename: str | None = 'screenshot.png'
    """
    Output filename
    """
    saveToFile: bool | None = True
    """
    Save screenshot to file system
    """
    includeTimestamp: bool | None = True
    """
    Include timestamp in filename
    """
    format: Format | None = 'png'
    """
    Output format
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    scrollIntoView: bool | None = True
    """
    Scroll element into view
    """
    fullPage: bool | None = False
    """
    Take full page screenshot
    """


class Type(StrEnum):
    """
    Type of form field
    """

    text = 'text'
    password = 'password'
    email = 'email'
    number = 'number'
    tel = 'tel'
    textarea = 'textarea'
    date = 'date'
    time = 'time'
    datetime_local = 'datetime-local'
    checkbox = 'checkbox'
    radio = 'radio'
    select = 'select'
    file = 'file'


class FormFieldOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    """
    Option value
    """
    label: str
    """
    Option label
    """


class Method(StrEnum):
    """
    HTTP method
    """

    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    DELETE = 'DELETE'
    PATCH = 'PATCH'


class ApiCallConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    method: Method | None = 'GET'
    """
    HTTP method
    """
    url: AnyUrl
    """
    API endpoint URL
    """
    headers: dict[str, str] | None = None
    """
    HTTP headers
    """
    body: str | None = None
    """
    Request body
    """
    outputVariable: str | None = 'apiResponse'
    """
    Variable to store response
    """
    timeout: int | None = 30000
    """
    Request timeout in milliseconds
    """
    retryCount: int | None = 0
    """
    Number of retries
    """
    parseJson: bool | None = True
    """
    Parse response as JSON
    """
    validateStatus: bool | None = True
    """
    Validate HTTP status code
    """
    followRedirects: bool | None = True
    """
    Follow HTTP redirects
    """
    verifySSL: bool | None = True
    """
    Verify SSL certificates
    """
    basicAuthUsername: str | None = None
    """
    Basic auth username
    """
    basicAuthPassword: str | None = None
    """
    Basic auth password
    """


class DatabaseQueryConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    connectionString: str
    """
    Database connection string
    """
    query: str
    """
    SQL query to execute
    """
    outputVariable: str | None = 'queryResult'
    """
    Variable to store result
    """
    logQuery: bool | None = True
    """
    Log the query being executed
    """
    validateConnection: bool | None = True
    """
    Validate database connection
    """
    timeout: int | None = 30000
    """
    Query timeout in milliseconds
    """


class DatabaseInsertConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    connectionString: str
    """
    Database connection string
    """
    table: str
    """
    Table name to insert into
    """
    data: dict[str, Any]
    """
    Data to insert (column-value pairs)
    """
    logOperation: bool | None = True
    """
    Log the insert operation
    """
    validateConnection: bool | None = True
    """
    Validate database connection
    """
    rollbackOnError: bool | None = True
    """
    Rollback transaction on error
    """


class FileUploadConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for file input
    """
    filePath: str
    """
    Path to file to upload
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    scrollIntoView: bool | None = True
    """
    Scroll element into view
    """
    validateFile: bool | None = True
    """
    Validate file exists before upload
    """


class FileDownloadConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for download link
    """
    downloadPath: str
    """
    Path to save downloaded file
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    validateDownload: bool | None = True
    """
    Validate download completed
    """
    overwriteExisting: bool | None = False
    """
    Overwrite existing files
    """


class CustomCodeConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: str
    """
    JavaScript code to execute
    """
    outputVariable: str | None = 'customResult'
    """
    Variable to store result
    """
    logExecution: bool | None = True
    """
    Log code execution
    """
    catchErrors: bool | None = True
    """
    Catch and handle errors
    """
    timeout: int | None = 30000
    """
    Execution timeout in milliseconds
    """


class SubflowConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    flowId: str
    """
    ID of flow to call
    """
    flowName: str | None = None
    """
    Name of flow to call
    """
    inputParameters: list[dict[str, Any]] | None = None
    """
    Input parameters for subflow
    """
    outputParameters: list[dict[str, Any]] | None = None
    """
    Output parameters from subflow
    """
    outputVariable: str | None = 'flowResult'
    """
    Variable to store result
    """
    waitForCompletion: bool | None = True
    """
    Wait for flow to complete
    """
    logExecution: bool | None = True
    """
    Log flow execution
    """
    propagateErrors: bool | None = True
    """
    Propagate errors from subflow
    """


class SendKeysConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str | None = None
    """
    CSS selector for element to send keys to
    """
    keys: str
    """
    Keys to send
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """


class Direction(StrEnum):
    """
    Scroll direction
    """

    up = 'up'
    down = 'down'
    left = 'left'
    right = 'right'


class ScrollConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    direction: Direction | None = 'down'
    """
    Scroll direction
    """
    distance: int | None = 100
    """
    Scroll distance in pixels
    """
    selector: str | None = None
    """
    Element to scroll (optional, defaults to window)
    """


class AssertVisibleConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for element to check
    """
    timeout: int | None = 5000
    """
    Timeout in milliseconds
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """


class ClearInputConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for input element
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """


class OpenNewTabConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    url: str
    """
    URL to open in new tab
    """


class SwitchTabConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    tabIndex: Annotated[int | None, Field(ge=0)] = None
    """
    Tab index to switch to
    """
    tabTitle: str | None = None
    """
    Tab title to switch to (alternative to index)
    """


class GoForwardConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class GoBackConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class RefreshConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class GetPageInfoConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    outputVariable: str | None = 'pageInfo'
    """
    Variable to store page information
    """


class JunctionConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    condition: str | None = None
    """
    Condition to evaluate
    """
    truePath: str | None = None
    """
    Path to take if condition is true
    """
    falsePath: str | None = None
    """
    Path to take if condition is false
    """


class Operator(StrEnum):
    """
    Comparison operator
    """

    equals = 'equals'
    not_equals = 'not_equals'
    greater_than = 'greater_than'
    less_than = 'less_than'
    greater_than_or_equal = 'greater_than_or_equal'
    less_than_or_equal = 'less_than_or_equal'
    contains = 'contains'
    not_contains = 'not_contains'
    starts_with = 'starts_with'
    ends_with = 'ends_with'
    exists = 'exists'
    not_exists = 'not_exists'
    is_empty = 'is_empty'
    not_empty = 'not_empty'
    is_true = 'is_true'
    is_false = 'is_false'
    in_ = 'in'
    not_in = 'not_in'
    matches = 'matches'
    not_matches = 'not_matches'


class ConditionalConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    condition: str
    """
    Variable name or {{variable_id}} pattern to evaluate
    """
    operator: Operator
    """
    Comparison operator
    """
    value: str
    """
    Value to compare against (can be plain text or {{variable_id}})
    """
    trueAction: str
    """
    Action ID to execute if condition is true
    """
    falseAction: str | None = None
    """
    Action ID to execute if condition is false
    """


class LoopType(StrEnum):
    """
    Type of loop
    """

    count_ = 'count'
    condition = 'condition'
    foreach = 'foreach'


class LoopConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    loopType: LoopType | None = 'count'
    """
    Type of loop
    """
    count: Annotated[int | None, Field(ge=1)] = None
    """
    Number of iterations (for count loops)
    """
    condition: str | None = None
    """
    Condition to continue loop (for condition loops)
    """
    arrayVariable: str | None = None
    """
    Variable containing array to iterate (for foreach loops)
    """
    itemVariable: str | None = 'item'
    """
    Variable name for current item (for foreach loops)
    """
    actions: list[dict[str, Any]]
    """
    Actions to execute in each iteration
    """
    maxIterations: Annotated[int | None, Field(ge=1)] = 100
    """
    Maximum iterations to prevent infinite loops
    """


class DragAndDropConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    sourceSelector: str
    """
    CSS selector for element to drag
    """
    targetSelector: str
    """
    CSS selector for drop target
    """
    waitForElement: bool | None = True
    """
    Wait for elements to be present
    """


class CallToFlowConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    flowId: str
    """
    ID of flow to call
    """
    inputParameters: dict[str, Any] | None = None
    """
    Input parameters to pass to subflow
    """
    outputVariable: str | None = 'flowResult'
    """
    Variable to store result
    """
    waitForCompletion: bool | None = True
    """
    Wait for subflow to complete
    """
    async_: Annotated[bool | None, Field(alias='async')] = False
    """
    Execute subflow asynchronously
    """


class SwitchToFrameConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    frameSelector: str | None = None
    """
    CSS selector or frame name/ID
    """
    frameIndex: Annotated[int | None, Field(ge=0)] = None
    """
    Frame index (alternative to selector)
    """


class ExitFrameConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class ViewportType(StrEnum):
    """
    Type of viewport configuration
    """

    preset = 'preset'
    device = 'device'
    responsive = 'responsive'
    custom = 'custom'


class SetViewportConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    viewportType: ViewportType | None = 'custom'
    """
    Type of viewport configuration
    """
    width: Annotated[int, Field(ge=1)]
    """
    Viewport width in pixels
    """
    height: Annotated[int, Field(ge=1)]
    """
    Viewport height in pixels
    """
    screenSizePreset: str | None = None
    """
    Preset screen size name
    """
    deviceName: str | None = None
    """
    Device name for emulation
    """
    deviceScaleFactor: Annotated[float | None, Field(ge=0.1, le=5.0)] = 1.0
    """
    Device scale factor
    """
    isMobile: bool | None = False
    """
    Emulate mobile device
    """
    hasTouch: bool | None = False
    """
    Enable touch events
    """
    isLandscape: bool | None = False
    """
    Use landscape orientation
    """
    userAgent: str | None = None
    """
    Custom user agent string
    """
    waitAfterResize: bool | None = True
    """
    Wait after viewport resize
    """
    takeScreenshot: bool | None = False
    """
    Take screenshot after resize
    """
    preserveCookies: bool | None = False
    """
    Preserve cookies across viewport changes
    """
    preserveLocalStorage: bool | None = False
    """
    Preserve local storage across viewport changes
    """
    preserveSessionStorage: bool | None = False
    """
    Preserve session storage across viewport changes
    """


class Property(StrEnum):
    text = 'text'
    value = 'value'
    class_ = 'class'
    id = 'id'
    tagName = 'tagName'
    innerHTML = 'innerHTML'
    outerHTML = 'outerHTML'
    attributes = 'attributes'
    rect = 'rect'
    visible = 'visible'
    enabled = 'enabled'
    selected = 'selected'


class GetElementPropertiesConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for element
    """
    properties: list[Property]
    """
    Properties to retrieve
    """
    outputVariable: str | None = 'elementProps'
    """
    Variable to store properties
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """


class Action(StrEnum):
    """
    Action to perform on popup
    """

    accept = 'accept'
    dismiss = 'dismiss'
    text = 'text'


class HandlePopupConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    action: Action | None = 'accept'
    """
    Action to perform on popup
    """
    text: str | None = None
    """
    Text to enter in prompt popup
    """
    waitForPopup: bool | None = True
    """
    Wait for popup to appear
    """
    timeout: int | None = 5000
    """
    Timeout in milliseconds
    """


class FormField(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector to target form field
    """
    value: Any
    """
    Value to fill
    """
    image: str | None = None
    """
    Optional screenshot path
    """
    name: str | None = None
    """
    Human-readable field name
    """
    type: Type | None = 'text'
    """
    Type of form field
    """
    options: list[FormFieldOption] | None = None
    """
    Options for select/radio fields
    """
    checked: bool | None = False
    """
    Whether checkbox is checked
    """
    multiple: bool | None = False
    """
    Whether select allows multiple selections
    """


class FormFillConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    fields: list[FormField]
    """
    Array of form field configurations
    """
    waitForElements: bool | None = True
    """
    Wait for all form elements to be present
    """
    clearFirst: bool | None = True
    """
    Clear existing values before filling
    """
    submitAfterFill: bool | None = False
    """
    Automatically submit form after filling
    """
    smartFieldDetection: bool | None = True
    """
    Automatically detect field types
    """


class ActionConfigurations(BaseModel):
    """
    Configuration schemas for all automation actions
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    actionConfigs: (
        dict[
            str,
            ClickConfig
            | InputConfig
            | SendKeysConfig
            | WaitConfig
            | NavigateConfig
            | ScrollConfig
            | ScreenshotConfig
            | AssertionConfig
            | AssertVisibleConfig
            | FormFillConfig
            | ClearInputConfig
            | OpenNewTabConfig
            | SwitchTabConfig
            | GoForwardConfig
            | GoBackConfig
            | RefreshConfig
            | GetPageInfoConfig
            | JunctionConfig
            | ApiCallConfig
            | ConditionalConfig
            | LoopConfig
            | DatabaseQueryConfig
            | DatabaseInsertConfig
            | CustomCodeConfig
            | DragAndDropConfig
            | CallToFlowConfig
            | SwitchToFrameConfig
            | ExitFrameConfig
            | SetViewportConfig
            | GetElementPropertiesConfig
            | HandlePopupConfig
            | FileUploadConfig
            | FileDownloadConfig
            | SubflowConfig,
        ]
        | None
    ) = None
