# generated by datamodel-codegen:
#   filename:  parallel-execution.json
#   timestamp: 2026-02-04T16:19:29+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Mode(StrEnum):
    """
    Execution mode
    """

    full = 'full'
    partial = 'partial'


class Flow(RootModel[Any]):
    root: Any


class Position(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x: float
    """
    X coordinate
    """
    y: float
    """
    Y coordinate
    """


class ActionData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    label: str
    """
    Human-readable label
    """
    type: str
    """
    Action type identifier
    """
    config: dict[str, Any]
    """
    Action-specific configuration
    """


class Action(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Unique action identifier
    """
    type: str
    """
    Action type
    """
    position: Position
    data: ActionData


class Edge(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Unique edge identifier
    """
    source: str
    """
    Source action ID
    """
    sourceHandle: str | None = None
    """
    Source handle identifier
    """
    target: str
    """
    Target action ID
    """
    targetHandle: str | None = None
    """
    Target handle identifier
    """
    type: str | None = 'step'
    """
    Edge type
    """
    data: dict[str, Any] | None = None
    """
    Additional edge data
    """


class Zoom(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x: float
    """
    Pan X position
    """
    y: float
    """
    Pan Y position
    """
    zoom: float
    """
    Zoom level
    """


class Variable(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Variable identifier
    """
    name: str
    """
    Variable name
    """
    type: str
    """
    Variable data type
    """
    value: str
    """
    Variable value
    """
    description: str | None = None
    """
    Optional description
    """
    isOutput: bool | None = None
    """
    Whether this is an output variable
    """


class FlowVariables(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    input: list[Variable]
    """
    Input variables
    """
    output: list[Variable]
    """
    Output variables
    """


class FlowParameters(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    input: list[Variable]
    """
    Input parameters
    """
    output: list[Variable]
    """
    Output parameters
    """


class EnvironmentVariable(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Variable identifier
    """
    name: str
    """
    Variable name
    """
    type: str
    """
    Variable data type
    """
    value: str
    """
    Variable value
    """
    description: str | None = None
    """
    Optional description
    """


class Environment(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Environment identifier
    """
    name: str
    """
    Environment name
    """
    variables: list[EnvironmentVariable]
    """
    Environment variables
    """
    description: str | None = None
    """
    Environment description
    """
    isDefault: bool | None = None
    """
    Whether this is the default environment
    """
    isActive: bool | None = None
    """
    Whether this environment is active
    """
    createdAt: AwareDatetime
    """
    Creation timestamp
    """
    updatedAt: AwareDatetime
    """
    Last update timestamp
    """


class GlobalVariable(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Variable identifier
    """
    name: str
    """
    Variable name
    """
    type: str
    """
    Variable data type
    """
    value: str
    """
    Variable value
    """
    description: str | None = None
    """
    Optional description
    """
    createdAt: AwareDatetime
    """
    Creation timestamp
    """
    updatedAt: AwareDatetime
    """
    Last update timestamp
    """


class Status(StrEnum):
    """
    Execution status
    """

    completed = 'completed'
    error = 'error'
    stopped = 'stopped'
    running = 'running'
    pending = 'pending'


class FlowExecutionResult(BaseModel):
    """
    Result of a single test execution
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    flow_id: str
    """
    ID of the executed flow
    """
    flow_name: str
    """
    Name of the executed flow
    """
    success: bool
    """
    Whether the test passed
    """
    status: Status
    """
    Execution status
    """
    total_actions: Annotated[int, Field(ge=0)]
    """
    Total actions in the flow
    """
    executed_actions: Annotated[int, Field(ge=0)]
    """
    Number of actions executed
    """
    successful_actions: Annotated[int, Field(ge=0)]
    """
    Number of successful actions
    """
    duration_seconds: Annotated[float, Field(ge=0.0)]
    """
    Total execution time in seconds
    """
    report: dict[str, Any]
    """
    Full flow report
    """
    error: str | None = None
    """
    Error message if failed
    """
    metadata: dict[str, Any] | None = {}
    """
    Additional test metadata
    """


class BrowserMode(StrEnum):
    """
    Browser mode
    """

    headful = 'headful'
    headless = 'headless'


class ParallelTestsResult(BaseModel):
    """
    Result of parallel test execution
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    total_tests: Annotated[int, Field(ge=0)]
    """
    Total number of tests
    """
    passed_tests: Annotated[int, Field(ge=0)]
    """
    Number of passed tests
    """
    failed_tests: Annotated[int, Field(ge=0)]
    """
    Number of failed tests
    """
    skipped_tests: Annotated[int | None, Field(ge=0)] = 0
    """
    Number of skipped tests
    """
    total_duration_seconds: Annotated[float, Field(ge=0.0)]
    """
    Total execution time
    """
    results: list[FlowExecutionResult]
    """
    Individual test results
    """
    success: bool
    """
    Overall success status
    """


class FlowExecutionRequest(BaseModel):
    """
    Request to execute a single test/flow
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    flow: Flow
    """
    Flow to execute with all required fields
    """
    mode: Mode | None = 'full'
    """
    Execution mode
    """
    recording: dict[str, Any] | None = None
    """
    Recording configuration
    """
    metadata: dict[str, Any] | None = {}
    """
    Additional test metadata
    """


class ParallelTestsRequest(BaseModel):
    """
    Request to execute multiple tests in parallel
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    tests: list[FlowExecutionRequest]
    """
    List of tests to execute
    """
    data: dict[str, Any] | None = None
    """
    Shared data containing environment and globalVariables for all tests
    """
    max_parallel: Annotated[int | None, Field(ge=1, le=50)] = 10
    """
    Maximum number of parallel executions
    """
    stop_on_failure: bool | None = False
    """
    Stop all tests if one fails
    """
    cleanup_after: bool | None = True
    """
    Cleanup resources after execution
    """
    browser_mode: BrowserMode | None = 'headful'
    """
    Browser mode
    """
    max_retries: Annotated[int | None, Field(ge=0, le=10)] = 3
    """
    Maximum retries for transient failures
    """


class ParallelExecution(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    requests: list[ParallelTestsRequest] | None = None
    results: list[ParallelTestsResult] | None = None


class ParallelExecutionModels(BaseModel):
    """
    Schema for parallel test execution requests and results
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    parallelExecution: ParallelExecution | None = None
