# generated by datamodel-codegen:
#   filename:  action-configs.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field

from ._base import FlowebActionBaseModel


class Identifiers(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    type: str | None = None
    confidence: float | None = None
    primary: bool | None = None
    unique: bool | None = None


class SemanticExpectedStates(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    checked: bool | None = None
    disabled: bool | None = None
    selected: bool | None = None
    expanded: bool | None = None


class SemanticRelation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    withinFormSelector: str | None = None


class SemanticLibraryHints(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    framework: str | None = None
    uiLibrary: str | None = None
    component: str | None = None


class SemanticTarget(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    tag: str | None = None
    role: str | None = None
    inputType: str | None = None
    name: str | None = None
    id: str | None = None
    text: str | None = None
    placeholder: str | None = None
    href: str | None = None
    classTokens: list[str] | None = None
    attributes: dict[str, str] | None = None
    libraryHints: SemanticLibraryHints | None = None
    expectedStates: SemanticExpectedStates | None = None
    relation: SemanticRelation | None = None


class ClickType(StrEnum):
    """
    Type of click to perform
    """

    left = 'left'
    right = 'right'


class WaitType(StrEnum):
    """
    Type of wait to perform
    """

    duration = 'duration'
    element = 'element'
    interactable = 'interactable'


class GeneratedBy(StrEnum):
    """
    Whether wait was generated manually or automatically
    """

    manual = 'manual'
    auto = 'auto'


class Reason(StrEnum):
    """
    Reason for automatic wait insertion
    """

    navigation = 'navigation'
    tab_switch = 'tab_switch'
    dom_transition = 'dom_transition'
    overlay = 'overlay'
    network_idle = 'network_idle'


class AssertType(StrEnum):
    """
    Type of assertion
    """

    exists = 'exists'
    visible = 'visible'
    text = 'text'
    value = 'value'
    attribute = 'attribute'


class ScreenshotType(StrEnum):
    """
    Type of screenshot to capture
    """

    viewport = 'viewport'
    fullPage = 'fullPage'
    element = 'element'


class Format(StrEnum):
    """
    Output format
    """

    png = 'png'
    jpg = 'jpg'


class Identifiers1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    type: str | None = None
    confidence: float | None = None


class Type(StrEnum):
    """
    Type of form field
    """

    text = 'text'
    password = 'password'
    email = 'email'
    number = 'number'
    tel = 'tel'
    textarea = 'textarea'
    date = 'date'
    time = 'time'
    datetime_local = 'datetime-local'
    checkbox = 'checkbox'
    radio = 'radio'
    select = 'select'
    file = 'file'


class FormFieldOption(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    """
    Option value
    """
    label: str
    """
    Option label
    """


class Method(StrEnum):
    """
    HTTP method
    """

    GET = 'GET'
    POST = 'POST'
    PUT = 'PUT'
    DELETE = 'DELETE'
    PATCH = 'PATCH'


class Direction(StrEnum):
    """
    Scroll direction
    """

    up = 'up'
    down = 'down'
    left = 'left'
    right = 'right'


class LoopType(StrEnum):
    """
    Type of loop
    """

    count_ = 'count'
    condition = 'condition'
    foreach = 'foreach'


class DropMode(StrEnum):
    """
    Drag mode: resolve by target element or by source-relative pointer offset
    """

    element = 'element'
    offset = 'offset'


class SourceIdentifiers(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    type: str | None = None
    confidence: float | None = None


class TargetIdentifiers(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    type: str | None = None
    confidence: float | None = None


class FrameIdentifiers(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    type: str | None = None
    confidence: float | None = None


class ViewportType(StrEnum):
    """
    Type of viewport configuration
    """

    preset = 'preset'
    device = 'device'
    responsive = 'responsive'
    custom = 'custom'


class Property(StrEnum):
    text = 'text'
    value = 'value'
    class_ = 'class'
    id = 'id'
    tagName = 'tagName'
    innerHTML = 'innerHTML'
    outerHTML = 'outerHTML'
    attributes = 'attributes'
    rect = 'rect'
    visible = 'visible'
    enabled = 'enabled'
    selected = 'selected'


class Action(StrEnum):
    """
    Action to perform on popup
    """

    accept = 'accept'
    dismiss = 'dismiss'
    text = 'text'


class Button(StrEnum):
    """
    Mouse button to use for clicking
    """

    left = 'left'
    right = 'right'
    middle = 'middle'


class Format1(StrEnum):
    """
    Screenshot image format
    """

    png = 'png'
    jpg = 'jpg'


class BaseActionConfig(FlowebActionBaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    image: str | None = None
    """
    Base64 encoded reference image
    """
    identifiers: list[str | Identifiers] | None = None
    """
    Ordered fallback identifiers to locate the target element
    """
    selectors: list[str] | None = None
    """
    Ordered fallback selectors to locate the target element
    """
    semanticTarget: SemanticTarget | None = None


class ClickConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for element to click
    """
    waitTime: int | None = 1000
    """
    Wait time in milliseconds
    """
    forceClick: bool | None = False
    """
    Force click even if element not clickable
    """
    scrollIntoView: bool | None = True
    """
    Scroll element into view before clicking
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    clickType: ClickType | None = 'left'
    """
    Type of click to perform
    """
    clickCount: Annotated[int | None, Field(ge=1)] = 1
    """
    Number of clicks to perform
    """
    clickAndHold: bool | None = False
    """
    Whether to click and hold
    """
    holdDuration: int | None = 1000
    """
    Duration to hold click in milliseconds
    """


class InputConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for input element
    """
    text: str
    """
    Text to input
    """
    clearFirst: bool | None = True
    """
    Clear field before typing
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    scrollIntoView: bool | None = True
    """
    Scroll element into view
    """


class NavigateConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    url: AnyUrl
    """
    URL to navigate to
    """
    waitForLoad: bool | None = True
    """
    Wait for page to load
    """
    takeScreenshot: bool | None = False
    """
    Take screenshot after navigation
    """


class WaitConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    waitType: WaitType | None = 'duration'
    """
    Type of wait to perform
    """
    duration: int | None = 3000
    """
    Duration to wait in milliseconds
    """
    selector: str | None = None
    """
    CSS selector for element to wait for
    """
    timeout: int | None = 10000
    """
    Maximum time to wait in milliseconds
    """
    waitForInteractable: bool | None = False
    """
    Wait for element to be interactable
    """
    fallbackToDuration: bool | None = True
    """
    Fallback to duration wait if element wait fails
    """
    fallbackDuration: int | None = 2000
    """
    Duration to wait if fallback triggered
    """
    generatedBy: GeneratedBy | None = None
    """
    Whether wait was generated manually or automatically
    """
    reason: Reason | None = None
    """
    Reason for automatic wait insertion
    """
    triggerActionId: str | None = None
    """
    Trigger action ID for auto-generated waits
    """
    effectiveWaitMs: Annotated[int | None, Field(ge=0)] = None
    """
    Observed elapsed wait between trigger and dependent action during recording
    """


class AssertionConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for element
    """
    assertType: AssertType | None = 'exists'
    """
    Type of assertion
    """
    expectedValue: str
    """
    Expected value for assertion
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    caseSensitive: bool | None = False
    """
    Case sensitive comparison
    """
    partialMatch: bool | None = False
    """
    Allow partial text matching
    """
    expectedImageRef: str | None = None
    """
    Image reference for image assertion (base64, data URI, or mediaId:xxx resolved to data URI)
    """
    imageSimilarityThreshold: float | None = 0.9
    """
    Minimum similarity score (0-1) for image assertions
    """


class ScreenshotConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    screenshotType: ScreenshotType | None = 'viewport'
    """
    Type of screenshot to capture
    """
    selector: str | None = None
    """
    CSS selector for element screenshots
    """
    filename: str | None = 'screenshot.png'
    """
    Output filename
    """
    saveToFile: bool | None = True
    """
    Save screenshot to file system
    """
    includeTimestamp: bool | None = True
    """
    Include timestamp in filename
    """
    format: Format | None = 'png'
    """
    Output format
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    scrollIntoView: bool | None = True
    """
    Scroll element into view
    """
    fullPage: bool | None = False
    """
    Take full page screenshot
    """


class FormField(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector to target form field
    """
    value: Any
    """
    Value to fill
    """
    image: str | None = None
    """
    Optional screenshot path
    """
    identifiers: list[str | Identifiers1] | None = None
    """
    Ordered fallback identifiers for this field
    """
    selectors: list[str] | None = None
    """
    Ordered fallback selectors for this field
    """
    semanticTarget: SemanticTarget | None = None
    name: str | None = None
    """
    Human-readable field name
    """
    type: Type | None = 'text'
    """
    Type of form field
    """
    options: list[FormFieldOption] | None = None
    """
    Options for select/radio fields
    """
    checked: bool | None = False
    """
    Whether checkbox is checked
    """
    multiple: bool | None = False
    """
    Whether select allows multiple selections
    """


class FormFillConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    fields: list[FormField]
    """
    Array of form field configurations
    """
    waitForElements: bool | None = True
    """
    Wait for all form elements to be present
    """
    clearFirst: bool | None = True
    """
    Clear existing values before filling
    """
    submitAfterFill: bool | None = False
    """
    Automatically submit form after filling
    """
    smartFieldDetection: bool | None = True
    """
    Automatically detect field types
    """


class ApiCallConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    method: Method | None = 'GET'
    """
    HTTP method
    """
    url: AnyUrl
    """
    API endpoint URL
    """
    headers: dict[str, str] | None = None
    """
    HTTP headers
    """
    body: str | None = None
    """
    Request body
    """
    outputVariable: str | None = 'apiResponse'
    """
    Variable to store response
    """
    responsePath: str | None = None
    """
    Optional path into the response to store in the output variable, e.g. data.token, headers["Content-Type"], data.items[0].id. Applied to the response object {status_code, headers, data, url} (body fields under data.). When empty, the full response object is stored.
    """
    timeout: int | None = 30000
    """
    Request timeout in milliseconds
    """
    retryCount: int | None = 0
    """
    Number of retries
    """
    parseJson: bool | None = True
    """
    Parse response as JSON
    """
    validateStatus: bool | None = True
    """
    Validate HTTP status code
    """
    followRedirects: bool | None = True
    """
    Follow HTTP redirects
    """
    verifySSL: bool | None = True
    """
    Verify SSL certificates
    """
    basicAuthUsername: str | None = None
    """
    Basic auth username
    """
    basicAuthPassword: str | None = None
    """
    Basic auth password
    """


class DatabaseQueryConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    connectionString: str
    """
    Database connection string
    """
    query: str
    """
    SQL query to execute
    """
    outputVariable: str | None = 'queryResult'
    """
    Variable to store result
    """
    logQuery: bool | None = True
    """
    Log the query being executed
    """
    validateConnection: bool | None = True
    """
    Validate database connection
    """
    timeout: int | None = 30000
    """
    Query timeout in milliseconds
    """


class DatabaseInsertConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    connectionString: str
    """
    Database connection string
    """
    table: str
    """
    Table name to insert into
    """
    data: dict[str, Any]
    """
    Data to insert (column-value pairs)
    """
    logOperation: bool | None = True
    """
    Log the insert operation
    """
    validateConnection: bool | None = True
    """
    Validate database connection
    """
    rollbackOnError: bool | None = True
    """
    Rollback transaction on error
    """


class FileUploadConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for file input
    """
    filePath: str
    """
    Path to file to upload
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    scrollIntoView: bool | None = True
    """
    Scroll element into view
    """
    validateFile: bool | None = True
    """
    Validate file exists before upload
    """


class FileDownloadConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for download link
    """
    downloadPath: str
    """
    Path to save downloaded file
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    validateDownload: bool | None = True
    """
    Validate download completed
    """
    overwriteExisting: bool | None = False
    """
    Overwrite existing files
    """


class CustomCodeConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: str
    """
    JavaScript code to execute
    """
    functionName: str | None = 'ExecuteFlowScript'
    """
    Main function name to invoke after loading the code
    """
    inputParameters: list[dict[str, Any]] | None = None
    """
    Input parameter mappings for the main function
    """
    outputVariable: str | None = 'customResult'
    """
    Variable to store result
    """
    logExecution: bool | None = True
    """
    Log code execution
    """
    catchErrors: bool | None = True
    """
    Catch and handle errors
    """
    timeout: int | None = 30000
    """
    Execution timeout in milliseconds
    """


class SubflowConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    flowId: str
    """
    ID of flow to call
    """
    flowName: str | None = None
    """
    Name of flow to call
    """
    inputParameters: list[dict[str, Any]] | None = None
    """
    Input parameters for subflow
    """
    outputParameters: list[dict[str, Any]] | None = None
    """
    Output parameters from subflow
    """
    outputVariable: str | None = 'flowResult'
    """
    Variable to store result
    """
    waitForCompletion: bool | None = True
    """
    Wait for flow to complete
    """
    logExecution: bool | None = True
    """
    Log flow execution
    """
    propagateErrors: bool | None = True
    """
    Propagate errors from subflow
    """


class SendKeysConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str | None = None
    """
    CSS selector for element to send keys to
    """
    keys: str
    """
    Keys to send
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    keyCombinations: list[Any] | None = None
    """
    Optional key combinations payload used by backend actions
    """


class ScrollConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    direction: Direction | None = 'down'
    """
    Scroll direction
    """
    distance: int | None = 100
    """
    Scroll distance in pixels
    """
    selector: str | None = None
    """
    Element to scroll (optional, defaults to window)
    """


class AssertVisibleConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for element to check
    """
    timeout: int | None = 5000
    """
    Timeout in milliseconds
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """


class ClearInputConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for input element
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """
    maintainFocus: bool | None = False
    """
    Whether to keep focus on element after clearing
    """


class OpenNewTabConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    url: str
    """
    URL to open in new tab
    """


class SwitchTabConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    tabIndex: Annotated[int | None, Field(ge=0)] = None
    """
    Tab index to switch to
    """
    tabTitle: str | None = None
    """
    Tab title to switch to (alternative to index)
    """
    tabUrl: str | None = None
    """
    URL of tab to switch to (alternative to index)
    """
    switchMethod: str | None = 'auto'
    """
    Explicit switch method (auto/index/url/title)
    """


class GoForwardConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class GoBackConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class RefreshConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class GetPageInfoConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    outputVariable: str | None = 'pageInfo'
    """
    Variable to store page information
    """
    outputKey: str | None = None
    """
    Dot-notation path to extract a specific key from the page info object (e.g. 'title', 'url'). If omitted, the full page info object is stored.
    """


class JunctionConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    condition: str | None = None
    """
    Condition to evaluate
    """
    truePath: str | None = None
    """
    Path to take if condition is true
    """
    falsePath: str | None = None
    """
    Path to take if condition is false
    """


class ConditionalConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    condition: str
    """
    JavaScript condition to evaluate
    """
    thenActions: list[dict[str, Any]] | None = None
    """
    Actions to execute if condition is true
    """
    elseActions: list[dict[str, Any]] | None = None
    """
    Actions to execute if condition is false
    """
    operator: str
    """
    Comparison operator used by editor helpers
    """


class LoopConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    loopType: LoopType | None = 'count'
    """
    Type of loop
    """
    count: Annotated[int | None, Field(ge=1)] = None
    """
    Number of iterations (for count loops)
    """
    condition: str | None = None
    """
    Condition to continue loop (for condition loops)
    """
    arrayVariable: str | None = None
    """
    Variable containing array to iterate (for foreach loops)
    """
    itemVariable: str | None = 'item'
    """
    Variable name for current item (for foreach loops)
    """
    actions: list[dict[str, Any]]
    """
    Actions to execute in each iteration
    """
    maxIterations: Annotated[int | None, Field(ge=1)] = 100
    """
    Maximum iterations to prevent infinite loops
    """


class DragAndDropConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    sourceSelector: str
    """
    CSS selector for element to drag
    """
    targetSelector: str | None = None
    """
    CSS selector for drop target (required in element mode)
    """
    dropMode: DropMode | None = 'element'
    """
    Drag mode: resolve by target element or by source-relative pointer offset
    """
    targetOffsetX: int | None = 0
    """
    Horizontal drag offset in pixels for offset mode
    """
    targetOffsetY: int | None = 0
    """
    Vertical drag offset in pixels for offset mode
    """
    targetValue: str | float | None = None
    """
    Explicit target value for range/slider controls
    """
    sourceIdentifiers: list[str | SourceIdentifiers] | None = None
    """
    Ordered fallback identifiers for drag source
    """
    sourceSelectors: list[str] | None = None
    """
    Ordered fallback selectors for drag source
    """
    targetIdentifiers: list[str | TargetIdentifiers] | None = None
    """
    Ordered fallback identifiers for drag target
    """
    targetSelectors: list[str] | None = None
    """
    Ordered fallback selectors for drag target
    """
    sourceSemanticTarget: SemanticTarget | None = None
    targetSemanticTarget: SemanticTarget | None = None
    waitForElement: bool | None = True
    """
    Wait for elements to be present
    """


class CallToFlowConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    flowId: str
    """
    ID of flow to call
    """
    inputParameters: dict[str, Any] | None = None
    """
    Input parameters to pass to subflow
    """
    outputVariable: str | None = 'flowResult'
    """
    Variable to store result
    """
    waitForCompletion: bool | None = True
    """
    Wait for subflow to complete
    """
    async_: bool | None = False
    """
    Execute subflow asynchronously
    """


class SwitchToFrameConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    frameSelector: str | None = None
    """
    CSS selector or frame name/ID
    """
    frameIdentifiers: list[str | FrameIdentifiers] | None = None
    """
    Ordered fallback identifiers for the frame element
    """
    frameSelectors: list[str] | None = None
    """
    Ordered fallback selectors for the frame element
    """
    frameSemanticTarget: SemanticTarget | None = None
    frameIndex: Annotated[int | None, Field(ge=0)] = None
    """
    Frame index (alternative to selector)
    """
    switchMethod: str | None = 'selector'
    """
    Switch strategy (selector/index/name/id)
    """
    frameName: str | None = None
    """
    Frame name (alternative to selector/index)
    """
    frameId: str | None = None
    """
    Frame id (alternative to selector/index)
    """
    waitForFrame: bool | None = True
    """
    Wait for frame to become available
    """


class ExitFrameConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    exitMethod: str | None = 'parent'
    """
    Exit strategy (parent/main/levels)
    """
    levels: Annotated[int | None, Field(ge=1)] = 1
    """
    Number of parent levels when exitMethod is levels
    """
    returnToMain: bool | None = False
    """
    Force returning to main content after exit
    """


class SetViewportConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    viewportType: ViewportType | None = 'custom'
    """
    Type of viewport configuration
    """
    width: Annotated[int, Field(ge=1)]
    """
    Viewport width in pixels
    """
    height: Annotated[int, Field(ge=1)]
    """
    Viewport height in pixels
    """
    screenSizePreset: str | None = None
    """
    Preset screen size name
    """
    deviceName: str | None = None
    """
    Device name for emulation
    """
    deviceScaleFactor: Annotated[float | None, Field(ge=0.1, le=5.0)] = 1.0
    """
    Device scale factor
    """
    isMobile: bool | None = False
    """
    Emulate mobile device
    """
    hasTouch: bool | None = False
    """
    Enable touch events
    """
    isLandscape: bool | None = False
    """
    Use landscape orientation
    """
    userAgent: str | None = None
    """
    Custom user agent string
    """
    waitAfterResize: bool | None = True
    """
    Wait after viewport resize
    """
    takeScreenshot: bool | None = False
    """
    Take screenshot after resize
    """
    preserveCookies: bool | None = False
    """
    Preserve cookies across viewport changes
    """
    preserveLocalStorage: bool | None = False
    """
    Preserve local storage across viewport changes
    """
    preserveSessionStorage: bool | None = False
    """
    Preserve session storage across viewport changes
    """


class GetElementPropertiesConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    selector: str
    """
    CSS selector for element
    """
    properties: list[Property]
    """
    Properties to retrieve
    """
    outputVariable: str | None = 'elementProps'
    """
    Variable to store properties
    """
    waitForElement: bool | None = True
    """
    Wait for element to be present
    """


class HandlePopupConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    action: Action | None = 'accept'
    """
    Action to perform on popup
    """
    text: str | None = None
    """
    Text to enter in prompt popup
    """
    waitForPopup: bool | None = True
    """
    Wait for popup to appear
    """
    timeout: int | None = 5000
    """
    Timeout in milliseconds
    """


class DesktopVisualBaseConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    confidence: Annotated[float | None, Field(ge=0.1, le=1.0)] = 0.82
    """
    Match threshold used for image detection
    """
    timeout: Annotated[int | None, Field(ge=0)] = 10000
    """
    Maximum wait time in milliseconds
    """
    pollIntervalMs: Annotated[int | None, Field(ge=50)] = 400
    """
    Polling interval while waiting for image matches
    """
    grayscale: bool | None = True
    """
    Use grayscale matching for better performance
    """
    useRegion: bool | None = False
    """
    Limit search to a specific screen region
    """
    regionX: int | None = 0
    """
    Region origin X coordinate
    """
    regionY: int | None = 0
    """
    Region origin Y coordinate
    """
    regionWidth: int | None = 0
    """
    Region width in pixels
    """
    regionHeight: int | None = 0
    """
    Region height in pixels
    """


class DesktopWaitForImageConfig(DesktopVisualBaseConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    image: str
    """
    Base64 encoded reference image to locate on the desktop
    """
    requireStability: bool | None = False
    """
    Require the image to remain visible for a stable period
    """
    stableDurationMs: Annotated[int | None, Field(ge=100)] = 600
    """
    How long the match should remain stable before succeeding
    """
    outputVariable: str | None = 'desktopMatch'
    """
    Variable to store desktop match metadata
    """
    failOnTimeout: bool | None = True
    """
    Fail action when image does not appear in time
    """


class DesktopFindImageConfig(DesktopVisualBaseConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    image: str
    """
    Base64 encoded reference image to locate on the desktop
    """
    waitForImage: bool | None = False
    """
    Wait for image appearance before returning
    """
    outputVariable: str | None = 'desktopFoundImage'
    """
    Variable to store found image match metadata
    """
    failIfNotFound: bool | None = False
    """
    Fail action when image cannot be located
    """


class DesktopClickImageConfig(DesktopVisualBaseConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    image: str
    """
    Base64 encoded reference image to click
    """
    button: Button | None = 'left'
    """
    Mouse button to use for clicking
    """
    clicks: Annotated[int | None, Field(ge=1)] = 1
    """
    Number of mouse clicks
    """
    intervalMs: Annotated[int | None, Field(ge=0)] = 120
    """
    Delay between multiple clicks in milliseconds
    """
    offsetX: int | None = 0
    """
    Horizontal click offset from detected center
    """
    offsetY: int | None = 0
    """
    Vertical click offset from detected center
    """
    waitForImage: bool | None = True
    """
    Wait until image appears before clicking
    """
    moveDurationMs: Annotated[int | None, Field(ge=0)] = 120
    """
    Mouse move duration before click
    """
    postActionWaitMs: Annotated[int | None, Field(ge=0)] = 300
    """
    Delay after click completes
    """


class DesktopClickPointConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x: int | None = 0
    """
    Target X coordinate
    """
    y: int | None = 0
    """
    Target Y coordinate
    """
    button: Button | None = 'left'
    """
    Mouse button to use for clicking
    """
    clicks: Annotated[int | None, Field(ge=1)] = 1
    """
    Number of mouse clicks
    """
    intervalMs: Annotated[int | None, Field(ge=0)] = 120
    """
    Delay between multiple clicks in milliseconds
    """
    moveDurationMs: Annotated[int | None, Field(ge=0)] = 120
    """
    Mouse move duration before click
    """
    postActionWaitMs: Annotated[int | None, Field(ge=0)] = 300
    """
    Delay after click completes
    """
    outputVariable: str | None = 'desktopLastClick'
    """
    Variable to store click coordinate metadata
    """


class DesktopTypeTextConfig(DesktopVisualBaseConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    text: str
    """
    Text to type on the desktop
    """
    intervalMs: Annotated[int | None, Field(ge=0)] = 25
    """
    Delay between key presses in milliseconds
    """
    clickImageFirst: bool | None = False
    """
    Click target image before typing to focus input
    """
    image: str | None = None
    """
    Optional target image used when clickImageFirst is enabled
    """
    waitForImage: bool | None = True
    """
    Wait for image before attempting focus click
    """
    clearBeforeType: bool | None = False
    """
    Select-all and clear before typing
    """
    submitWithEnter: bool | None = False
    """
    Press Enter after typing
    """
    postActionWaitMs: Annotated[int | None, Field(ge=0)] = 300
    """
    Delay after typing completes
    """


class DesktopMoveMouseConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x: int | None = 0
    """
    Target X coordinate
    """
    y: int | None = 0
    """
    Target Y coordinate
    """
    relative: bool | None = False
    """
    Treat x and y as offsets from current pointer location
    """
    moveDurationMs: Annotated[int | None, Field(ge=0)] = 120
    """
    Mouse move duration
    """
    postActionWaitMs: Annotated[int | None, Field(ge=0)] = 100
    """
    Delay after pointer move completes
    """
    outputVariable: str | None = 'desktopPointer'
    """
    Variable to store pointer position metadata
    """


class DesktopHotkeyConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    keyCombination: str
    """
    Key combination (e.g. ctrl+shift+p)
    """
    presses: Annotated[int | None, Field(ge=1)] = 1
    """
    How many times to trigger the hotkey
    """
    intervalMs: Annotated[int | None, Field(ge=0)] = 120
    """
    Delay between repeated hotkeys in milliseconds
    """
    postActionWaitMs: Annotated[int | None, Field(ge=0)] = 150
    """
    Delay after hotkey execution
    """


class DesktopRunCommandConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: str
    """
    Shell command to execute
    """
    shell: bool | None = True
    """
    Run command through shell
    """
    workingDirectory: str | None = None
    """
    Optional working directory for command execution
    """
    timeout: Annotated[int | None, Field(ge=0)] = 60000
    """
    Command timeout in milliseconds
    """
    captureOutput: bool | None = True
    """
    Capture stdout and stderr
    """
    failOnNonZero: bool | None = True
    """
    Fail action when command exits with non-zero code
    """
    outputVariable: str | None = 'desktopCommandResult'
    """
    Variable to store command result details
    """


class DesktopCaptureScreenConfig(BaseActionConfig):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    filename: str | None = 'desktop-screenshot.png'
    """
    Output filename when saving screenshot
    """
    saveToFile: bool | None = True
    """
    Persist screenshot to screenshots folder
    """
    includeTimestamp: bool | None = True
    """
    Append timestamp to output filename
    """
    format: Format1 | None = 'png'
    """
    Screenshot image format
    """
    useRegion: bool | None = False
    """
    Capture a specific region of the desktop
    """
    regionX: int | None = 0
    regionY: int | None = 0
    regionWidth: int | None = 0
    regionHeight: int | None = 0
    outputVariable: str | None = 'desktopScreenshot'
    """
    Variable to store screenshot metadata and base64 content
    """


class ActionConfigurations(BaseModel):
    """
    Configuration schemas for all automation actions
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    actionConfigs: (
        dict[
            str,
            ClickConfig
            | InputConfig
            | SendKeysConfig
            | WaitConfig
            | NavigateConfig
            | ScrollConfig
            | ScreenshotConfig
            | AssertionConfig
            | AssertVisibleConfig
            | FormFillConfig
            | ClearInputConfig
            | OpenNewTabConfig
            | SwitchTabConfig
            | GoForwardConfig
            | GoBackConfig
            | RefreshConfig
            | GetPageInfoConfig
            | JunctionConfig
            | ApiCallConfig
            | ConditionalConfig
            | LoopConfig
            | DatabaseQueryConfig
            | DatabaseInsertConfig
            | CustomCodeConfig
            | DragAndDropConfig
            | CallToFlowConfig
            | SwitchToFrameConfig
            | ExitFrameConfig
            | SetViewportConfig
            | GetElementPropertiesConfig
            | HandlePopupConfig
            | FileUploadConfig
            | FileDownloadConfig
            | SubflowConfig
            | DesktopWaitForImageConfig
            | DesktopFindImageConfig
            | DesktopClickImageConfig
            | DesktopClickPointConfig
            | DesktopTypeTextConfig
            | DesktopMoveMouseConfig
            | DesktopHotkeyConfig
            | DesktopRunCommandConfig
            | DesktopCaptureScreenConfig,
        ]
        | None
    ) = None
