# generated by datamodel-codegen:
#   filename:  action-configs.json
#   timestamp: 2026-02-04T16:10:52+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AnyUrl, BaseModel, Field


class BaseActionConfig(BaseModel):
    image: str | None = Field(None, description="Base64 encoded reference image")


class ClickType(StrEnum):
    """
    Type of click to perform
    """

    left = "left"
    right = "right"


class ClickConfig(BaseActionConfig):
    selector: str = Field(..., description="CSS selector for element to click")
    wait_time: int | None = Field(
        1000, alias="waitTime", description="Wait time in milliseconds"
    )
    force_click: bool | None = Field(
        False,
        alias="forceClick",
        description="Force click even if element not clickable",
    )
    scroll_into_view: bool | None = Field(
        True,
        alias="scrollIntoView",
        description="Scroll element into view before clicking",
    )
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )
    click_type: ClickType | None = Field(
        "left", alias="clickType", description="Type of click to perform"
    )
    click_count: int | None = Field(
        1, alias="clickCount", description="Number of clicks to perform", ge=1
    )
    click_and_hold: bool | None = Field(
        False, alias="clickAndHold", description="Whether to click and hold"
    )
    hold_duration: int | None = Field(
        1000, alias="holdDuration", description="Duration to hold click in milliseconds"
    )


class InputConfig(BaseActionConfig):
    selector: str = Field(..., description="CSS selector for input element")
    text: str = Field(..., description="Text to input")
    clear_first: bool | None = Field(
        True, alias="clearFirst", description="Clear field before typing"
    )
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )
    scroll_into_view: bool | None = Field(
        True, alias="scrollIntoView", description="Scroll element into view"
    )


class NavigateConfig(BaseActionConfig):
    url: AnyUrl = Field(..., description="URL to navigate to")
    wait_for_load: bool | None = Field(
        True, alias="waitForLoad", description="Wait for page to load"
    )
    take_screenshot: bool | None = Field(
        False, alias="takeScreenshot", description="Take screenshot after navigation"
    )


class WaitType(StrEnum):
    """
    Type of wait to perform
    """

    duration = "duration"
    element = "element"
    interactable = "interactable"


class WaitConfig(BaseActionConfig):
    wait_type: WaitType | None = Field(
        "duration", alias="waitType", description="Type of wait to perform"
    )
    duration: int | None = Field(3000, description="Duration to wait in milliseconds")
    selector: str | None = Field(
        None, description="CSS selector for element to wait for"
    )
    timeout: int | None = Field(
        10000, description="Maximum time to wait in milliseconds"
    )
    wait_for_interactable: bool | None = Field(
        False,
        alias="waitForInteractable",
        description="Wait for element to be interactable",
    )
    fallback_to_duration: bool | None = Field(
        True,
        alias="fallbackToDuration",
        description="Fallback to duration wait if element wait fails",
    )
    fallback_duration: int | None = Field(
        2000,
        alias="fallbackDuration",
        description="Duration to wait if fallback triggered",
    )


class AssertType(StrEnum):
    """
    Type of assertion
    """

    exists = "exists"
    visible = "visible"
    text = "text"
    value = "value"
    attribute = "attribute"


class AssertionConfig(BaseActionConfig):
    selector: str = Field(..., description="CSS selector for element")
    assert_type: AssertType | None = Field(
        "exists", alias="assertType", description="Type of assertion"
    )
    expected_value: str = Field(
        ..., alias="expectedValue", description="Expected value for assertion"
    )
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )
    case_sensitive: bool | None = Field(
        False, alias="caseSensitive", description="Case sensitive comparison"
    )
    partial_match: bool | None = Field(
        False, alias="partialMatch", description="Allow partial text matching"
    )


class ScreenshotType(StrEnum):
    """
    Type of screenshot to capture
    """

    viewport = "viewport"
    full_page = "fullPage"
    element = "element"


class Format(StrEnum):
    """
    Output format
    """

    png = "png"
    jpg = "jpg"


class ScreenshotConfig(BaseActionConfig):
    screenshot_type: ScreenshotType | None = Field(
        "viewport", alias="screenshotType", description="Type of screenshot to capture"
    )
    selector: str | None = Field(
        None, description="CSS selector for element screenshots"
    )
    filename: str | None = Field("screenshot.png", description="Output filename")
    save_to_file: bool | None = Field(
        True, alias="saveToFile", description="Save screenshot to file system"
    )
    include_timestamp: bool | None = Field(
        True, alias="includeTimestamp", description="Include timestamp in filename"
    )
    format: Format | None = Field("png", description="Output format")
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )
    scroll_into_view: bool | None = Field(
        True, alias="scrollIntoView", description="Scroll element into view"
    )
    full_page: bool | None = Field(
        False, alias="fullPage", description="Take full page screenshot"
    )


class Type(StrEnum):
    """
    Type of form field
    """

    text = "text"
    password = "password"
    email = "email"
    number = "number"
    tel = "tel"
    textarea = "textarea"
    date = "date"
    time = "time"
    datetime_local = "datetime-local"
    checkbox = "checkbox"
    radio = "radio"
    select = "select"
    file = "file"


class FormFieldOption(BaseModel):
    value: str = Field(..., description="Option value")
    label: str = Field(..., description="Option label")


class Method(StrEnum):
    """
    HTTP method
    """

    get = "GET"
    post = "POST"
    put = "PUT"
    delete = "DELETE"
    patch = "PATCH"


class ApiCallConfig(BaseActionConfig):
    method: Method | None = Field("GET", description="HTTP method")
    url: AnyUrl = Field(..., description="API endpoint URL")
    headers: dict[str, str] | None = Field(None, description="HTTP headers")
    body: str | None = Field(None, description="Request body")
    output_variable: str | None = Field(
        "apiResponse", alias="outputVariable", description="Variable to store response"
    )
    timeout: int | None = Field(30000, description="Request timeout in milliseconds")
    retry_count: int | None = Field(
        0, alias="retryCount", description="Number of retries"
    )
    parse_json: bool | None = Field(
        True, alias="parseJson", description="Parse response as JSON"
    )
    validate_status: bool | None = Field(
        True, alias="validateStatus", description="Validate HTTP status code"
    )
    follow_redirects: bool | None = Field(
        True, alias="followRedirects", description="Follow HTTP redirects"
    )
    verify_ssl: bool | None = Field(
        True, alias="verifySSL", description="Verify SSL certificates"
    )
    basic_auth_username: str | None = Field(
        None, alias="basicAuthUsername", description="Basic auth username"
    )
    basic_auth_password: str | None = Field(
        None, alias="basicAuthPassword", description="Basic auth password"
    )


class DatabaseQueryConfig(BaseActionConfig):
    connection_string: str = Field(
        ..., alias="connectionString", description="Database connection string"
    )
    query: str = Field(..., description="SQL query to execute")
    output_variable: str | None = Field(
        "queryResult", alias="outputVariable", description="Variable to store result"
    )
    log_query: bool | None = Field(
        True, alias="logQuery", description="Log the query being executed"
    )
    validate_connection: bool | None = Field(
        True, alias="validateConnection", description="Validate database connection"
    )
    timeout: int | None = Field(30000, description="Query timeout in milliseconds")


class DatabaseInsertConfig(BaseActionConfig):
    connection_string: str = Field(
        ..., alias="connectionString", description="Database connection string"
    )
    table: str = Field(..., description="Table name to insert into")
    data: dict[str, Any] = Field(..., description="Data to insert (column-value pairs)")
    log_operation: bool | None = Field(
        True, alias="logOperation", description="Log the insert operation"
    )
    validate_connection: bool | None = Field(
        True, alias="validateConnection", description="Validate database connection"
    )
    rollback_on_error: bool | None = Field(
        True, alias="rollbackOnError", description="Rollback transaction on error"
    )


class FileUploadConfig(BaseActionConfig):
    selector: str = Field(..., description="CSS selector for file input")
    file_path: str = Field(..., alias="filePath", description="Path to file to upload")
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )
    scroll_into_view: bool | None = Field(
        True, alias="scrollIntoView", description="Scroll element into view"
    )
    validate_file: bool | None = Field(
        True, alias="validateFile", description="Validate file exists before upload"
    )


class FileDownloadConfig(BaseActionConfig):
    selector: str = Field(..., description="CSS selector for download link")
    download_path: str = Field(
        ..., alias="downloadPath", description="Path to save downloaded file"
    )
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )
    validate_download: bool | None = Field(
        True, alias="validateDownload", description="Validate download completed"
    )
    overwrite_existing: bool | None = Field(
        False, alias="overwriteExisting", description="Overwrite existing files"
    )


class CustomCodeConfig(BaseActionConfig):
    code: str = Field(..., description="JavaScript code to execute")
    output_variable: str | None = Field(
        "customResult", alias="outputVariable", description="Variable to store result"
    )
    log_execution: bool | None = Field(
        True, alias="logExecution", description="Log code execution"
    )
    catch_errors: bool | None = Field(
        True, alias="catchErrors", description="Catch and handle errors"
    )
    timeout: int | None = Field(30000, description="Execution timeout in milliseconds")


class SubflowConfig(BaseActionConfig):
    flow_id: str = Field(..., alias="flowId", description="ID of flow to call")
    flow_name: str | None = Field(
        None, alias="flowName", description="Name of flow to call"
    )
    input_parameters: list[dict[str, Any]] | None = Field(
        None, alias="inputParameters", description="Input parameters for subflow"
    )
    output_parameters: list[dict[str, Any]] | None = Field(
        None, alias="outputParameters", description="Output parameters from subflow"
    )
    output_variable: str | None = Field(
        "flowResult", alias="outputVariable", description="Variable to store result"
    )
    wait_for_completion: bool | None = Field(
        True, alias="waitForCompletion", description="Wait for flow to complete"
    )
    log_execution: bool | None = Field(
        True, alias="logExecution", description="Log flow execution"
    )
    propagate_errors: bool | None = Field(
        True, alias="propagateErrors", description="Propagate errors from subflow"
    )


class SendKeysConfig(BaseActionConfig):
    selector: str | None = Field(
        None, description="CSS selector for element to send keys to"
    )
    keys: str = Field(..., description="Keys to send")
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )


class Direction(StrEnum):
    """
    Scroll direction
    """

    up = "up"
    down = "down"
    left = "left"
    right = "right"


class ScrollConfig(BaseActionConfig):
    direction: Direction | None = Field("down", description="Scroll direction")
    distance: int | None = Field(100, description="Scroll distance in pixels")
    selector: str | None = Field(
        None, description="Element to scroll (optional, defaults to window)"
    )


class AssertVisibleConfig(BaseActionConfig):
    selector: str = Field(..., description="CSS selector for element to check")
    timeout: int | None = Field(5000, description="Timeout in milliseconds")
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )


class ClearInputConfig(BaseActionConfig):
    selector: str = Field(..., description="CSS selector for input element")
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )


class OpenNewTabConfig(BaseActionConfig):
    url: str = Field(..., description="URL to open in new tab")


class SwitchTabConfig(BaseActionConfig):
    tab_index: int | None = Field(
        None, alias="tabIndex", description="Tab index to switch to", ge=0
    )
    tab_title: str | None = Field(
        None,
        alias="tabTitle",
        description="Tab title to switch to (alternative to index)",
    )


class GoForwardConfig(BaseActionConfig):
    pass


class GoBackConfig(BaseActionConfig):
    pass


class RefreshConfig(BaseActionConfig):
    pass


class GetPageInfoConfig(BaseActionConfig):
    output_variable: str | None = Field(
        "pageInfo",
        alias="outputVariable",
        description="Variable to store page information",
    )


class JunctionConfig(BaseActionConfig):
    condition: str | None = Field(None, description="Condition to evaluate")
    true_path: str | None = Field(
        None, alias="truePath", description="Path to take if condition is true"
    )
    false_path: str | None = Field(
        None, alias="falsePath", description="Path to take if condition is false"
    )


class Operator(StrEnum):
    """
    Comparison operator
    """

    equals = "equals"
    not_equals = "not_equals"
    greater_than = "greater_than"
    less_than = "less_than"
    greater_than_or_equal = "greater_than_or_equal"
    less_than_or_equal = "less_than_or_equal"
    contains = "contains"
    not_contains = "not_contains"
    starts_with = "starts_with"
    ends_with = "ends_with"
    exists = "exists"
    not_exists = "not_exists"
    is_empty = "is_empty"
    not_empty = "not_empty"
    is_true = "is_true"
    is_false = "is_false"
    in_ = "in"
    not_in = "not_in"
    matches = "matches"
    not_matches = "not_matches"


class ConditionalConfig(BaseActionConfig):
    condition: str = Field(
        ..., description="Variable name or {{variable_id}} pattern to evaluate"
    )
    operator: Operator = Field(..., description="Comparison operator")
    value: str = Field(
        ...,
        description="Value to compare against (can be plain text or {{variable_id}})",
    )
    true_action: str = Field(
        ..., alias="trueAction", description="Action ID to execute if condition is true"
    )
    false_action: str | None = Field(
        None,
        alias="falseAction",
        description="Action ID to execute if condition is false",
    )


class LoopType(StrEnum):
    """
    Type of loop
    """

    count_ = "count"
    condition = "condition"
    foreach = "foreach"


class LoopConfig(BaseActionConfig):
    loop_type: LoopType | None = Field(
        "count", alias="loopType", description="Type of loop"
    )
    count: int | None = Field(
        None, description="Number of iterations (for count loops)", ge=1
    )
    condition: str | None = Field(
        None, description="Condition to continue loop (for condition loops)"
    )
    array_variable: str | None = Field(
        None,
        alias="arrayVariable",
        description="Variable containing array to iterate (for foreach loops)",
    )
    item_variable: str | None = Field(
        "item",
        alias="itemVariable",
        description="Variable name for current item (for foreach loops)",
    )
    actions: list[dict[str, Any]] = Field(
        ..., description="Actions to execute in each iteration"
    )
    max_iterations: int | None = Field(
        100,
        alias="maxIterations",
        description="Maximum iterations to prevent infinite loops",
        ge=1,
    )


class DragAndDropConfig(BaseActionConfig):
    source_selector: str = Field(
        ..., alias="sourceSelector", description="CSS selector for element to drag"
    )
    target_selector: str = Field(
        ..., alias="targetSelector", description="CSS selector for drop target"
    )
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for elements to be present"
    )


class CallToFlowConfig(BaseActionConfig):
    flow_id: str = Field(..., alias="flowId", description="ID of flow to call")
    input_parameters: dict[str, Any] | None = Field(
        None, alias="inputParameters", description="Input parameters to pass to subflow"
    )
    output_variable: str | None = Field(
        "flowResult", alias="outputVariable", description="Variable to store result"
    )
    wait_for_completion: bool | None = Field(
        True, alias="waitForCompletion", description="Wait for subflow to complete"
    )
    async_: bool | None = Field(
        False, alias="async", description="Execute subflow asynchronously"
    )


class SwitchToFrameConfig(BaseActionConfig):
    frame_selector: str | None = Field(
        None, alias="frameSelector", description="CSS selector or frame name/ID"
    )
    frame_index: int | None = Field(
        None,
        alias="frameIndex",
        description="Frame index (alternative to selector)",
        ge=0,
    )


class ExitFrameConfig(BaseActionConfig):
    pass


class ViewportType(StrEnum):
    """
    Type of viewport configuration
    """

    preset = "preset"
    device = "device"
    responsive = "responsive"
    custom = "custom"


class SetViewportConfig(BaseActionConfig):
    viewport_type: ViewportType | None = Field(
        "custom", alias="viewportType", description="Type of viewport configuration"
    )
    width: int = Field(..., description="Viewport width in pixels", ge=1)
    height: int = Field(..., description="Viewport height in pixels", ge=1)
    screen_size_preset: str | None = Field(
        None, alias="screenSizePreset", description="Preset screen size name"
    )
    device_name: str | None = Field(
        None, alias="deviceName", description="Device name for emulation"
    )
    device_scale_factor: float | None = Field(
        1.0,
        alias="deviceScaleFactor",
        description="Device scale factor",
        ge=0.1,
        le=5.0,
    )
    is_mobile: bool | None = Field(
        False, alias="isMobile", description="Emulate mobile device"
    )
    has_touch: bool | None = Field(
        False, alias="hasTouch", description="Enable touch events"
    )
    is_landscape: bool | None = Field(
        False, alias="isLandscape", description="Use landscape orientation"
    )
    user_agent: str | None = Field(
        None, alias="userAgent", description="Custom user agent string"
    )
    wait_after_resize: bool | None = Field(
        True, alias="waitAfterResize", description="Wait after viewport resize"
    )
    take_screenshot: bool | None = Field(
        False, alias="takeScreenshot", description="Take screenshot after resize"
    )
    preserve_cookies: bool | None = Field(
        False,
        alias="preserveCookies",
        description="Preserve cookies across viewport changes",
    )
    preserve_local_storage: bool | None = Field(
        False,
        alias="preserveLocalStorage",
        description="Preserve local storage across viewport changes",
    )
    preserve_session_storage: bool | None = Field(
        False,
        alias="preserveSessionStorage",
        description="Preserve session storage across viewport changes",
    )


class Property(StrEnum):
    text = "text"
    value = "value"
    class_ = "class"
    id = "id"
    tag_name = "tagName"
    inner_html = "innerHTML"
    outer_html = "outerHTML"
    attributes = "attributes"
    rect = "rect"
    visible = "visible"
    enabled = "enabled"
    selected = "selected"


class GetElementPropertiesConfig(BaseActionConfig):
    selector: str = Field(..., description="CSS selector for element")
    properties: list[Property] = Field(..., description="Properties to retrieve")
    output_variable: str | None = Field(
        "elementProps",
        alias="outputVariable",
        description="Variable to store properties",
    )
    wait_for_element: bool | None = Field(
        True, alias="waitForElement", description="Wait for element to be present"
    )


class Action(StrEnum):
    """
    Action to perform on popup
    """

    accept = "accept"
    dismiss = "dismiss"
    text = "text"


class HandlePopupConfig(BaseActionConfig):
    action: Action | None = Field("accept", description="Action to perform on popup")
    text: str | None = Field(None, description="Text to enter in prompt popup")
    wait_for_popup: bool | None = Field(
        True, alias="waitForPopup", description="Wait for popup to appear"
    )
    timeout: int | None = Field(5000, description="Timeout in milliseconds")


class FormField(BaseModel):
    selector: str = Field(..., description="CSS selector to target form field")
    value: Any = Field(..., description="Value to fill")
    image: str | None = Field(None, description="Optional screenshot path")
    name: str | None = Field(None, description="Human-readable field name")
    type: Type | None = Field("text", description="Type of form field")
    options: list[FormFieldOption] | None = Field(
        None, description="Options for select/radio fields"
    )
    checked: bool | None = Field(False, description="Whether checkbox is checked")
    multiple: bool | None = Field(
        False, description="Whether select allows multiple selections"
    )


class FormFillConfig(BaseActionConfig):
    fields: list[FormField] = Field(
        ..., description="Array of form field configurations"
    )
    wait_for_elements: bool | None = Field(
        True,
        alias="waitForElements",
        description="Wait for all form elements to be present",
    )
    clear_first: bool | None = Field(
        True, alias="clearFirst", description="Clear existing values before filling"
    )
    submit_after_fill: bool | None = Field(
        False,
        alias="submitAfterFill",
        description="Automatically submit form after filling",
    )
    smart_field_detection: bool | None = Field(
        True,
        alias="smartFieldDetection",
        description="Automatically detect field types",
    )


class ActionConfigurations(BaseModel):
    """
    Configuration schemas for all automation actions
    """

    action_configs: (
        dict[
            str,
            ClickConfig
            | InputConfig
            | SendKeysConfig
            | WaitConfig
            | NavigateConfig
            | ScrollConfig
            | ScreenshotConfig
            | AssertionConfig
            | AssertVisibleConfig
            | FormFillConfig
            | ClearInputConfig
            | OpenNewTabConfig
            | SwitchTabConfig
            | GoForwardConfig
            | GoBackConfig
            | RefreshConfig
            | GetPageInfoConfig
            | JunctionConfig
            | ApiCallConfig
            | ConditionalConfig
            | LoopConfig
            | DatabaseQueryConfig
            | DatabaseInsertConfig
            | CustomCodeConfig
            | DragAndDropConfig
            | CallToFlowConfig
            | SwitchToFrameConfig
            | ExitFrameConfig
            | SetViewportConfig
            | GetElementPropertiesConfig
            | HandlePopupConfig
            | FileUploadConfig
            | FileDownloadConfig
            | SubflowConfig,
        ]
        | None
    ) = Field(None, alias="actionConfigs")
