# generated by datamodel-codegen:
#   filename:  action-types.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict


class ActionType(StrEnum):
    """
    Every automation action-type identifier (29 web + 18 desktop + 3 api + 4 integrations + 6 core = 60).
    """

    click = 'click'
    input = 'input'
    sendKeys = 'sendKeys'
    wait = 'wait'
    navigate = 'navigate'
    scroll = 'scroll'
    screenshot = 'screenshot'
    assertion = 'assertion'
    assertVisible = 'assertVisible'
    fillForm = 'fillForm'
    clearInput = 'clearInput'
    openNewTab = 'openNewTab'
    switchTab = 'switchTab'
    goForward = 'goForward'
    goBack = 'goBack'
    refresh = 'refresh'
    getPageInfo = 'getPageInfo'
    setViewport = 'setViewport'
    apiCall = 'apiCall'
    networkControl = 'networkControl'
    accessibilityAudit = 'accessibilityAudit'
    captureWebVitals = 'captureWebVitals'
    visualRegression = 'visualRegression'
    loadDataset = 'loadDataset'
    conditional = 'conditional'
    loop = 'loop'
    dbQuery = 'dbQuery'
    dbInsert = 'dbInsert'
    custom = 'custom'
    dragAndDrop = 'dragAndDrop'
    callToFlow = 'callToFlow'
    switchToFrame = 'switchToFrame'
    exitFrame = 'exitFrame'
    getElementProperties = 'getElementProperties'
    handlePopup = 'handlePopup'
    fileUpload = 'fileUpload'
    fileDownload = 'fileDownload'
    junction = 'junction'
    desktopWaitForImage = 'desktopWaitForImage'
    desktopVerifyImage = 'desktopVerifyImage'
    desktopFindImage = 'desktopFindImage'
    desktopClickImage = 'desktopClickImage'
    desktopClickPoint = 'desktopClickPoint'
    desktopTypeText = 'desktopTypeText'
    desktopFillForm = 'desktopFillForm'
    desktopMoveMouse = 'desktopMoveMouse'
    desktopDragAndDrop = 'desktopDragAndDrop'
    desktopHotkey = 'desktopHotkey'
    desktopRunCommand = 'desktopRunCommand'
    desktopRunScript = 'desktopRunScript'
    desktopCaptureScreen = 'desktopCaptureScreen'
    desktopFocusWindow = 'desktopFocusWindow'
    desktopOpenApplication = 'desktopOpenApplication'
    desktopSwitchDesktop = 'desktopSwitchDesktop'
    desktopListProcesses = 'desktopListProcesses'
    desktopOpenPath = 'desktopOpenPath'
    gmail = 'gmail'
    slack = 'slack'
    discord = 'discord'
    jira = 'jira'


class DesktopActionType(StrEnum):
    """
    The 18 desktop automation action types (subset of ActionType).
    """

    desktopWaitForImage = 'desktopWaitForImage'
    desktopVerifyImage = 'desktopVerifyImage'
    desktopFindImage = 'desktopFindImage'
    desktopClickImage = 'desktopClickImage'
    desktopClickPoint = 'desktopClickPoint'
    desktopTypeText = 'desktopTypeText'
    desktopFillForm = 'desktopFillForm'
    desktopMoveMouse = 'desktopMoveMouse'
    desktopDragAndDrop = 'desktopDragAndDrop'
    desktopHotkey = 'desktopHotkey'
    desktopRunCommand = 'desktopRunCommand'
    desktopRunScript = 'desktopRunScript'
    desktopCaptureScreen = 'desktopCaptureScreen'
    desktopFocusWindow = 'desktopFocusWindow'
    desktopOpenApplication = 'desktopOpenApplication'
    desktopSwitchDesktop = 'desktopSwitchDesktop'
    desktopListProcesses = 'desktopListProcesses'
    desktopOpenPath = 'desktopOpenPath'


class IntegrationActionType(StrEnum):
    """
    Actions that call an external application's API.
    """

    gmail = 'gmail'
    slack = 'slack'
    discord = 'discord'
    jira = 'jira'


class WebActionType(StrEnum):
    """
    The 29 browser/DOM action types that require a live page context (subset of ActionType).
    """

    click = 'click'
    input = 'input'
    sendKeys = 'sendKeys'
    scroll = 'scroll'
    dragAndDrop = 'dragAndDrop'
    fillForm = 'fillForm'
    clearInput = 'clearInput'
    assertion = 'assertion'
    assertVisible = 'assertVisible'
    getElementProperties = 'getElementProperties'
    switchToFrame = 'switchToFrame'
    exitFrame = 'exitFrame'
    handlePopup = 'handlePopup'
    fileUpload = 'fileUpload'
    fileDownload = 'fileDownload'
    navigate = 'navigate'
    goForward = 'goForward'
    goBack = 'goBack'
    refresh = 'refresh'
    openNewTab = 'openNewTab'
    switchTab = 'switchTab'
    getPageInfo = 'getPageInfo'
    setViewport = 'setViewport'
    screenshot = 'screenshot'
    custom = 'custom'
    networkControl = 'networkControl'
    accessibilityAudit = 'accessibilityAudit'
    captureWebVitals = 'captureWebVitals'
    visualRegression = 'visualRegression'


class ApiActionType(StrEnum):
    """
    The 3 direct service-call action types: generic HTTP calls and database queries (subset of ActionType).
    """

    apiCall = 'apiCall'
    dbQuery = 'dbQuery'
    dbInsert = 'dbInsert'


class CoreActionType(StrEnum):
    """
    The 6 platform-agnostic control-flow and generic utility action types that need neither a browser nor OS automation (subset of ActionType).
    """

    conditional = 'conditional'
    loop = 'loop'
    junction = 'junction'
    callToFlow = 'callToFlow'
    wait = 'wait'
    loadDataset = 'loadDataset'


class ActionTypes(BaseModel):
    """
    Canonical registry of automation action-type identifiers. The runtime strings are uniform camelCase across all consumers (AI catalog, backend factory/recorder, frontend, config classes); this schema is the single source. Config class names still diverge from the string in some cases (fillForm->FormFillConfig, dbQuery->DatabaseQueryConfig, dbInsert->DatabaseInsertConfig, custom->CustomCodeConfig) — that alignment is tracked in the backend/action-configs plans, not here.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    actionType: ActionType | None = None
