# generated by datamodel-codegen:
#   filename:  ai-contracts.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class AIProviderType(StrEnum):
    """
    AI provider selector
    """

    auto = 'auto'
    ollama = 'ollama'
    openai = 'openai'
    anthropic = 'anthropic'
    openai_compatible = 'openai-compatible'
    disabled = 'disabled'


class AIProviderConfig(BaseModel):
    """
    Provider/model selection for an AI request
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider: AIProviderType | None = 'auto'
    model: str | None = None
    baseUrl: str | None = None
    apiKey: str | None = None
    temperature: float | None = 0.2
    maxTokens: int | None = 2000
    requestTimeoutSeconds: Annotated[float | None, Field(ge=10.0, le=900.0)] = None
    """
    How long to wait for the model to respond, in seconds. Null uses the service default. Bounded so a client cannot hold a worker open indefinitely.
    """


class AIRequestMetadata(BaseModel):
    """
    Server-injected request context. Accepts additional keys.
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    accountId: str | None = None
    userId: str | None = None
    traceId: str | None = None


class Source(StrEnum):
    llm = 'llm'
    heuristic = 'heuristic'


class AIResponseMetadata(BaseModel):
    """
    Provenance attached to every AI response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    provider: str
    model: str
    source: Source
    warnings: list[str] | None = []
    raw: dict[str, Any] | None = None


class FlowStep(BaseModel):
    """
    A high-level generated flow step
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    name: str
    action: str
    description: str | None = ''
    parameters: dict[str, Any] | None = {}


class GenerateFlowRequest(BaseModel):
    """
    POST /ai/generate-flow request
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    url: str | None = None
    currentTest: dict[str, Any] | None = None
    provider: AIProviderConfig | None = None
    metadata: AIRequestMetadata | None = None


class GenerateFlowResponse(BaseModel):
    """
    POST /ai/generate-flow response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    nodes: list[dict[str, Any]]
    edges: list[dict[str, Any]]
    steps: list[FlowStep]
    variables: list[dict[str, Any]] | None = []
    testData: dict[str, Any] | None = {}
    metadata: AIResponseMetadata
    message: str


class AssistantOperation(BaseModel):
    """
    One tool operation proposed/performed by the assistant
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    tool: str
    payload: dict[str, Any] | None = {}
    summary: str | None = None


class AssistantToolDescriptor(BaseModel):
    """
    A registered assistant tool (GET /ai/assistant-tools)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    label: str
    description: str
    category: str
    requiresExecution: bool


class Mode(StrEnum):
    partial = 'partial'
    full = 'full'


class AssistantRunRequest(BaseModel):
    """
    The assistant asking for the test to be executed so it can check its own work. `partial` runs only what it changed; `full` runs everything.
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    mode: Mode
    reason: str
    """
    Why the run is needed, shown to the user when asking permission
    """
    nodeIds: list[str] | None = []
    """
    Nodes to run for a partial run. The client prepends whatever setup steps are required, so a mid-flow action does not fail for want of a browser.
    """
    expectation: str | None = None
    """
    What the assistant expects to happen, so a mismatch is meaningful
    """


class Status(StrEnum):
    passed = 'passed'
    failed = 'failed'
    error = 'error'
    cancelled = 'cancelled'
    not_run = 'not_run'


class AssistantRunOutcome(BaseModel):
    """
    Execution results handed back to the assistant so it can decide whether to fix, continue, or stop.
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    status: Status
    mode: Mode
    durationSeconds: float | None = None
    failedNodeId: str | None = None
    failedAction: str | None = None
    errorMessage: str | None = None
    steps: list[dict[str, Any]] | None = []
    """
    Per-step outcomes from the engine report
    """
    consoleLogs: list[str] | None = []
    reportId: str | None = None


class AssistantContinuation(BaseModel):
    """
    Set when the assistant could not finish in one turn. The client applies this turn, then sends `nextInstruction` back to continue, so progress is visible per step instead of after the whole goal.
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    goal: str
    """
    The overall objective being worked towards
    """
    nextInstruction: str
    """
    Instruction the client should send to continue
    """
    remaining: int | None = None
    """
    Best estimate of turns still needed, when known
    """
    reason: str | None = None
    """
    Why the work was split
    """


class AssistantPhase(StrEnum):
    """
    Coarse stage of an assistant turn, streamed while the turn runs
    """

    reading_context = 'reading_context'
    consulting_docs = 'consulting_docs'
    awaiting_model = 'awaiting_model'
    executing_tools = 'executing_tools'
    done = 'done'
    failed = 'failed'
    cancelled = 'cancelled'


class AssistantProgressEvent(BaseModel):
    """
    One server-sent event emitted while an assistant turn runs. Terminal events carry the final response.
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    phase: AssistantPhase
    label: str
    """
    Human-readable description of the current phase
    """
    detail: str | None = None
    """
    Optional extra context for the phase
    """
    response: dict[str, Any] | None = None
    """
    The completed AssistantActionResponse, present only on a terminal event
    """


class AssistantStepKind(StrEnum):
    """
    What kind of work a thread step represents
    """

    discovery = 'discovery'
    decision = 'decision'
    edit = 'edit'
    answer = 'answer'
    error = 'error'


class Status1(StrEnum):
    ok = 'ok'
    skipped = 'skipped'
    failed = 'failed'


class AssistantStep(BaseModel):
    """
    One entry in the assistant's reasoning thread: what it looked at, what it decided, and what it changed
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    id: str
    kind: AssistantStepKind
    title: str
    detail: str | None = None
    """
    Longer explanation shown when expanded. Markdown.
    """
    tool: str | None = None
    """
    Tool this step corresponds to, when it maps to one
    """
    status: Status1 | None = 'ok'


class FixLocatorRequest(BaseModel):
    """
    POST /ai/fix-locator request
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    dom: str
    oldLocator: str
    attemptedSelectors: list[str] | None = []
    failedSelectors: list[str] | None = []
    semanticTarget: dict[str, Any] | None = None
    actionType: str | None = None
    provider: AIProviderConfig | None = None
    metadata: AIRequestMetadata | None = None


class FixLocatorResponse(BaseModel):
    """
    POST /ai/fix-locator response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    locator: str
    confidence: float
    alternatives: list[str] | None = []
    metadata: AIResponseMetadata
    reasoning: str | None = None


class AnalyzeFailureRequest(BaseModel):
    """
    POST /ai/analyze-failure request
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    failedStep: dict[str, Any] | None = None
    dom: str | None = None
    screenshot: str | None = None
    consoleLogs: list[str] | None = []
    networkLogs: list[dict[str, Any]] | None = []
    errorMessage: str | None = None
    provider: AIProviderConfig | None = None
    metadata: AIRequestMetadata | None = None


class AnalyzeFailureResponse(BaseModel):
    """
    POST /ai/analyze-failure response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    cause: str
    fix: str
    confidence: float
    metadata: AIResponseMetadata
    recommendations: list[str] | None = []


class OptimizeRecordingRequest(BaseModel):
    """
    POST /ai/optimize-recording request
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    flowName: str | None = 'Recorded Flow'
    recordedActions: list[dict[str, Any]] | None = []
    provider: AIProviderConfig | None = None
    metadata: AIRequestMetadata | None = None


class OptimizeRecordingResponse(BaseModel):
    """
    POST /ai/optimize-recording response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    flow: dict[str, Any]
    optimizedActions: list[dict[str, Any]] | None = []
    removedActions: int | None = 0
    metadata: AIResponseMetadata
    message: str


class VibeAction(BaseModel):
    """
    A vibe-mode action decision
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: str
    label: str | None = ''
    description: str | None = ''
    config: dict[str, Any] | None = {}


class VibeStepRecord(BaseModel):
    """
    A prior vibe step in history
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: str | None = ''
    label: str | None = ''
    reasoning: str | None = ''
    success: bool | None = True
    message: str | None = ''


class VibeMessage(BaseModel):
    """
    A conversational message for vibe mode
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: str | None = 'user'
    content: str | None = ''


class VibeExistingStep(BaseModel):
    """
    An already-authored step passed as context
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: str | None = ''
    label: str | None = ''


class VibeNextActionRequest(BaseModel):
    """
    POST /ai/vibe-next-action request
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    instruction: str
    screenshot: str
    """
    base64 / data URI
    """
    screenWidth: int | None = 0
    screenHeight: int | None = 0
    step: int | None = 1
    maxSteps: int | None = 25
    history: Annotated[list[VibeStepRecord] | None, Field(default_factory=list)]
    messages: Annotated[list[VibeMessage] | None, Field(default_factory=list)]
    existingSteps: Annotated[list[VibeExistingStep] | None, Field(default_factory=list)]
    provider: AIProviderConfig | None = None
    metadata: AIRequestMetadata | None = None


class VibeNextActionResponse(BaseModel):
    """
    POST /ai/vibe-next-action response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    done: bool | None = False
    reasoning: str | None = ''
    message: str | None = ''
    expectation: str | None = ''
    action: VibeAction | None = None
    metadata: AIResponseMetadata


class VibeVerifyRequest(BaseModel):
    """
    POST /ai/vibe-verify request
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    instruction: str
    screenshot: str
    """
    post-action screenshot (base64)
    """
    expectation: str
    lastAction: VibeAction | None = None
    step: int | None = 1
    provider: AIProviderConfig | None = None
    metadata: AIRequestMetadata | None = None


class AutonomousTestsRequest(BaseModel):
    """
    POST /ai/generate-tests request. Crawls the URL server-side, so the body carries a target rather than a description; bounds mirror the ai-service's GenerateTestsRequest.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    url: Annotated[str, Field(max_length=2048, min_length=5)]
    goal: Annotated[str | None, Field(max_length=2000)] = None
    maxSuites: Annotated[int | None, Field(ge=1, le=10)] = None
    provider: AIProviderConfig | None = None


class VibeVerifyResponse(BaseModel):
    """
    POST /ai/vibe-verify response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    verified: bool | None = False
    reason: str | None = ''
    metadata: AIResponseMetadata


class AIContracts(BaseModel):
    """
    Request/response contracts for the AI service routes. Authored in canonical camelCase (the aliases the Pydantic models already accept via populate_by_name). NOTE: the ai-service currently emits snake_case for a few aliased response fields (testData, optimizedActions, removedActions) unless dumped by_alias; aligning that is ai-service Phase 3. The floweb-server proxy defines requests only and passes responses through opaquely. There is NO generate-tests route; the two extra routes are vibe-next-action and vibe-verify.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    generateFlowRequest: GenerateFlowRequest | None = None
    generateFlowResponse: GenerateFlowResponse | None = None
    providerConfig: AIProviderConfig | None = None
    autonomousTestsRequest: AutonomousTestsRequest | None = None


class AssistantActionRequest(BaseModel):
    """
    POST /ai/assistant-actions request
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    instruction: str
    currentTest: dict[str, Any] | None = None
    assistantPermissions: dict[str, Any] | None = None
    runOutcome: AssistantRunOutcome | None = None
    """
    Results of a run the assistant previously requested
    """
    engineConnected: bool | None = None
    """
    Whether the engine is reachable, so the assistant knows if running is possible
    """
    provider: AIProviderConfig | None = None
    metadata: AIRequestMetadata | None = None


class AssistantActionResponse(BaseModel):
    """
    POST /ai/assistant-actions response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    message: str
    operations: Annotated[list[AssistantOperation] | None, Field(default_factory=list)]
    plan: list[str] | None = None
    suggestions: list[str] | None = None
    steps: Annotated[list[AssistantStep] | None, Field(default_factory=list)]
    continuation: AssistantContinuation | None = None
    runRequest: AssistantRunRequest | None = None
    metadata: AIResponseMetadata
