# generated by datamodel-codegen:
#   filename:  api-key.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ApiKeyScope(StrEnum):
    """
    What a key is permitted to do. 'runs:execute' triggers test runs; 'runs:read' reads runs and reports.
    """

    runs_execute = 'runs:execute'
    runs_read = 'runs:read'


class ApiKeyStatus(StrEnum):
    """
    Derived state of a key. Keys are never extended: an expired or revoked key is replaced by a new one.
    """

    active = 'active'
    expired = 'expired'
    revoked = 'revoked'


class ApiKey(BaseModel):
    """
    An API key as returned by the API. Never carries the secret.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: str
    accountId: str
    name: Annotated[str, Field(max_length=100, min_length=1)]
    """
    Human label shown in the UI and recorded on runs this key starts.
    """
    keyPrefix: str
    """
    Leading, non-secret portion of the key, so a key can be identified in a list without revealing it.
    """
    scopes: Annotated[list[ApiKeyScope], Field(min_length=1)]
    status: ApiKeyStatus
    createdBy: str
    """
    User who created the key. Retained for audit; the key itself is the initiator of its runs.
    """
    createdAt: AwareDatetime
    expiresAt: AwareDatetime | None = None
    """
    Fixed at creation and immutable. Null means the key does not expire.
    """
    revokedAt: AwareDatetime | None = None
    lastUsedAt: AwareDatetime | None = None


class CreateApiKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    name: Annotated[str, Field(max_length=100, min_length=1)]
    scopes: Annotated[list[ApiKeyScope] | None, Field(min_length=1)] = None
    expiresInDays: Annotated[int | None, Field(ge=1, le=3650)] = None
    """
    Lifetime in days, fixed at creation. Omit or null for a key that does not expire.
    """


class CreateApiKeyResponse(BaseModel):
    """
    Returned once at creation. This is the only time the secret is available.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    apiKey: ApiKey
    secret: str
    """
    The full key. Never stored in plaintext and never retrievable again.
    """


class APIKeyModels(BaseModel):
    """
    Account-scoped API keys used to authenticate non-interactive runs (CI/CD). The secret is shown once at creation and only ever stored as a hash.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    apiKeys: list[ApiKey] | None = None
