# generated by datamodel-codegen:
#   filename:  billing.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class PlanId(StrEnum):
    """
    Billing plan identifier. 'custom' is assigned manually by a Floweb administrator.
    """

    basic = 'basic'
    premium = 'premium'
    max = 'max'
    custom = 'custom'


class FeatureId(StrEnum):
    """
    A gateable product capability. Every enforcement point in the server, engine and UI keys off one of these.
    """

    test_creation = 'test_creation'
    test_execution = 'test_execution'
    reporting = 'reporting'
    advanced_analytics = 'advanced_analytics'
    recorder = 'recorder'
    self_healing_basic = 'self_healing_basic'
    self_healing_ai = 'self_healing_ai'
    ai_assistant = 'ai_assistant'
    ai_test_generation = 'ai_test_generation'
    ai_vibe_testing = 'ai_vibe_testing'
    parallel_execution = 'parallel_execution'
    performance_testing = 'performance_testing'


class SubscriptionStatus(StrEnum):
    """
    Lifecycle state of an account subscription. Only 'active' and 'trialing' grant entitlements.
    """

    active = 'active'
    trialing = 'trialing'
    past_due = 'past_due'
    cancelled = 'cancelled'


class PaymentStatus(StrEnum):
    """
    Outcome of a simulated payment attempt
    """

    succeeded = 'succeeded'
    failed = 'failed'
    refunded = 'refunded'


class BillingInterval(StrEnum):
    """
    Billing cadence for a plan price
    """

    monthly = 'monthly'
    yearly = 'yearly'


class PlanQuotas(BaseModel):
    """
    Numeric limits attached to a plan. A null value means unlimited.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    executionsPerDay: Annotated[int | None, Field(ge=0)]
    maxTests: Annotated[int | None, Field(ge=0)] = None
    maxMembers: Annotated[int | None, Field(ge=0)] = None


class PlanCatalogEntry(BaseModel):
    """
    A purchasable plan as advertised on the billing page
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: PlanId
    name: Annotated[str, Field(max_length=60)]
    description: Annotated[str, Field(max_length=300)]
    priceMonthly: Annotated[float | None, Field(ge=0.0)] = None
    priceYearly: Annotated[float | None, Field(ge=0.0)] = None
    currency: str | None = 'USD'
    features: list[FeatureId]
    quotas: PlanQuotas
    highlights: list[str] | None = None
    contactOnly: bool | None = False


class PaymentRecord(BaseModel):
    """
    A simulated payment attempt retained for the billing history table. No real gateway is involved and no card data is stored.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    planId: PlanId
    amount: Annotated[float, Field(ge=0.0)]
    currency: str | None = 'USD'
    interval: BillingInterval | None = None
    status: PaymentStatus
    cardLast4: Annotated[str | None, Field(max_length=4)] = None
    reference: str | None = None
    """
    Simulated gateway reference
    """
    createdAt: AwareDatetime


class FeatureOverride(BaseModel):
    """
    An administrator-set grant or revocation of a single feature, applied on top of the plan's feature list
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    feature: FeatureId
    enabled: bool
    note: Annotated[str | None, Field(max_length=200)] = None


class UsageSnapshot(BaseModel):
    """
    Consumption for the current UTC day, used to enforce executionsPerDay
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    date: str
    """
    UTC day key, YYYY-MM-DD
    """
    executions: Annotated[int, Field(ge=0)]
    executionsLimit: Annotated[int | None, Field(ge=0)] = None
    executionsRemaining: Annotated[int | None, Field(ge=0)] = None
    creditsRemaining: Annotated[int | None, Field(ge=0)] = None
    """
    Admin-granted credits left after this execution; spent only once the plan allowance is exhausted
    """


class FeatureDeniedReason(StrEnum):
    """
    Why an entitlement check failed, so callers can render the right call to action
    """

    not_in_plan = 'not_in_plan'
    quota_exceeded = 'quota_exceeded'
    subscription_inactive = 'subscription_inactive'
    disabled_by_user = 'disabled_by_user'
    spend_cap_reached = 'spend_cap_reached'
    allowance_exhausted = 'allowance_exhausted'
    invoice_unpaid = 'invoice_unpaid'


class MeteredMetric(StrEnum):
    """
    A countable unit of consumption. Distinct from FeatureId: a feature is gateable, a metric is billable. Every metric that maps to a gated capability is enforced through that feature as well.
    """

    test_execution = 'test_execution'
    suite_execution = 'suite_execution'
    api_test_execution = 'api_test_execution'
    performance_test_run = 'performance_test_run'
    test_creation = 'test_creation'
    crawl_generation = 'crawl_generation'
    recorder_session = 'recorder_session'
    ai_test_generation = 'ai_test_generation'
    ai_assistant_message = 'ai_assistant_message'
    ai_vibe_testing = 'ai_vibe_testing'
    self_healing_ai = 'self_healing_ai'
    seat = 'seat'


class BillingModel(StrEnum):
    """
    How an account is charged. 'fixed' bills a recurring amount and caps each metric with an allowance; 'pay_as_you_go' bills per unit consumed plus an optional per-seat charge.
    """

    fixed = 'fixed'
    pay_as_you_go = 'pay_as_you_go'


class MetricAllowance(BaseModel):
    """
    A fixed plan's ceiling for one metric. A null limit means unlimited. Daily limits reset at 00:00 UTC; monthly limits reset on the account's anniversary.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    metric: MeteredMetric
    limitPerDay: Annotated[int | None, Field(ge=0)] = None
    limitPerMonth: Annotated[int | None, Field(ge=0)] = None


class MetricPrice(BaseModel):
    """
    Pay-as-you-go unit price for one metric, set by a Floweb administrator and agreed by the account before it takes effect.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    metric: MeteredMetric
    unitPrice: Annotated[float, Field(ge=0.0)]
    unit: Annotated[str | None, Field(max_length=40)] = None
    """
    Human label for one billable unit, e.g. 'per execution'
    """


class SpendCapScope(StrEnum):
    """
    Whether a cap applies to the whole account or to each individual member.
    """

    account = 'account'
    user = 'user'


class SpendCap(BaseModel):
    """
    A ceiling set by the account owner or admin on pay-as-you-go spend. Enforcement triggers when the cap is reached, not exceeded, so the final chargeable action is the one that meets the limit. Account and user caps are both enforced and the stricter one wins.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    scope: SpendCapScope
    limitDaily: Annotated[float | None, Field(ge=0.0)] = None
    limitMonthly: Annotated[float | None, Field(ge=0.0)] = None
    userId: str | None = None
    """
    Set only for a per-member override of the account's user-scope default
    """


class CatalogueStatus(StrEnum):
    """
    Lifecycle of an administrator-authored pricing proposal. A catalogue is negotiated in a support thread first and only becomes payable once the account has approved it there and an administrator has released it to billing. Only an 'accepted' catalogue grants entitlements.
    """

    draft = 'draft'
    in_negotiation = 'in_negotiation'
    client_approved = 'client_approved'
    revision_requested = 'revision_requested'
    sent = 'sent'
    accepted = 'accepted'
    declined = 'declined'
    superseded = 'superseded'
    expired = 'expired'


class PricingCatalogue(BaseModel):
    """
    A per-account pricing proposal authored by a Floweb administrator. Negotiated in a support thread, then released to the account's billing page for payment. Immutable once proposed: a revision creates a new catalogue pointing at the previous one via revisionOf, so the negotiation history stays auditable. Terms are copied onto the subscription when accepted, so later catalogue edits never retroactively change what an account agreed to.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    accountId: str | None = None
    """
    Account the catalogue is for; null for one quoted offline before an account exists
    """
    billingModel: BillingModel
    name: Annotated[str, Field(max_length=80)]
    summary: Annotated[str | None, Field(max_length=500)] = None
    currency: str | None = 'USD'
    baseMonthlyPrice: Annotated[float | None, Field(ge=0.0)] = None
    """
    Recurring charge for a fixed catalogue; null for pure pay-as-you-go
    """
    seatPriceMonthly: Annotated[float | None, Field(ge=0.0)] = None
    """
    Per-member monthly charge, counted from active account members at invoice time
    """
    allowances: list[MetricAllowance]
    """
    Populated for a fixed catalogue
    """
    prices: list[MetricPrice]
    """
    Populated for a pay-as-you-go catalogue
    """
    features: list[FeatureId]
    """
    Capabilities the catalogue unlocks
    """
    status: CatalogueStatus
    ticketId: str | None = None
    """
    Support thread the catalogue was negotiated in
    """
    revisionOf: str | None = None
    """
    Catalogue this one supersedes
    """
    validUntil: AwareDatetime | None = None
    createdByAdminId: str | None = None
    createdByAdminEmail: str | None = None
    sentAt: AwareDatetime | None = None
    respondedAt: AwareDatetime | None = None
    acceptedByUserId: str | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None
    proposedAt: AwareDatetime | None = None
    """
    When it was posted into the support thread for the account to review
    """
    clientRespondedAt: AwareDatetime | None = None
    clientResponseNote: Annotated[str | None, Field(max_length=1000)] = None
    """
    What the account said when approving or asking for a revision
    """


class MetricUsage(BaseModel):
    """
    Consumption of one metric over a window, with the money it accrued. Cost is zero on a fixed catalogue, where allowances rather than prices apply.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    metric: MeteredMetric
    count: Annotated[int, Field(ge=0)]
    cost: Annotated[float, Field(ge=0.0)]
    limitPerDay: Annotated[int | None, Field(ge=0)] = None
    limitPerMonth: Annotated[int | None, Field(ge=0)] = None
    remainingToday: Annotated[int | None, Field(ge=0)] = None
    remainingThisMonth: Annotated[int | None, Field(ge=0)] = None


class SpendState(BaseModel):
    """
    Where an account or member stands against its spend caps right now. blocked is true once a cap is reached, which refuses further chargeable actions until the cap is raised.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    scope: SpendCapScope
    userId: str | None = None
    spentToday: Annotated[float, Field(ge=0.0)]
    spentThisMonth: Annotated[float, Field(ge=0.0)]
    limitDaily: Annotated[float | None, Field(ge=0.0)] = None
    limitMonthly: Annotated[float | None, Field(ge=0.0)] = None
    blocked: bool
    blockedReason: str | None = None


class InvoiceStatus(StrEnum):
    """
    Lifecycle of a generated invoice. 'open' is billed and awaiting payment; 'void' was cancelled by an administrator.
    """

    draft = 'draft'
    open = 'open'
    paid = 'paid'
    past_due = 'past_due'
    void = 'void'


class InvoiceLineKind(StrEnum):
    """
    What an invoice line represents.
    """

    base = 'base'
    seat = 'seat'
    metric = 'metric'
    credit_grant = 'credit_grant'
    adjustment = 'adjustment'


class InvoiceLine(BaseModel):
    """
    One charge on an invoice. amount is quantity times unitPrice, stored rather than derived so a later price change cannot alter an issued invoice.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: InvoiceLineKind
    metric: MeteredMetric | None = None
    description: Annotated[str, Field(max_length=200)]
    quantity: Annotated[float, Field(ge=0.0)]
    unitPrice: Annotated[float, Field(ge=0.0)]
    amount: float


class Invoice(BaseModel):
    """
    A billing statement for one period, generated on the account's anniversary. Lines are frozen at issue time.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    number: str | None = None
    """
    Human-facing invoice number
    """
    accountId: str
    accountName: str | None = None
    billingModel: BillingModel
    currency: str | None = 'USD'
    periodStart: AwareDatetime
    periodEnd: AwareDatetime
    lines: list[InvoiceLine]
    subtotal: float
    creditsApplied: Annotated[float | None, Field(ge=0.0)] = None
    total: float
    status: InvoiceStatus
    issuedAt: AwareDatetime
    dueAt: AwareDatetime | None = None
    paidAt: AwareDatetime | None = None
    paymentReference: str | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class CreditRequestStatus(StrEnum):
    """
    Lifecycle of an account's request for additional credits.
    """

    requested = 'requested'
    quoted = 'quoted'
    accepted = 'accepted'
    granted = 'granted'
    declined = 'declined'


class CreditRequest(BaseModel):
    """
    A structured request for additional credits, raised from the billing page and negotiated in a support thread. Once granted, the quoted amount is added to the account's next invoice.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    accountId: str
    requestedByUserId: str
    requestedByEmail: str | None = None
    metric: MeteredMetric | None = None
    """
    Metric the credits are for; null means general-purpose credits
    """
    quantity: Annotated[int, Field(ge=1)]
    reason: Annotated[str, Field(max_length=1000)]
    status: CreditRequestStatus
    quotedUnitPrice: Annotated[float | None, Field(ge=0.0)] = None
    quotedTotal: Annotated[float | None, Field(ge=0.0)] = None
    currency: str | None = 'USD'
    ticketId: str | None = None
    grantedAt: AwareDatetime | None = None
    invoiceId: str | None = None
    """
    Invoice the granted credits were charged on
    """
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class TicketPayloadKind(StrEnum):
    """
    What a structured support-thread message carries, beyond its text.
    """

    catalogue_proposal = 'catalogue_proposal'
    catalogue_approval = 'catalogue_approval'
    catalogue_revision_request = 'catalogue_revision_request'
    credit_quote = 'credit_quote'
    credit_acceptance = 'credit_acceptance'


class TicketCommentPayload(BaseModel):
    """
    A structured attachment on a support comment. The comment's own text stays the human message; this carries what the UI needs to render an actionable card and to link the thread to the billing document it is about.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: TicketPayloadKind
    catalogueId: str | None = None
    creditRequestId: str | None = None
    summary: Annotated[str | None, Field(max_length=300)] = None
    """
    One-line description shown on the card
    """
    amount: Annotated[float | None, Field(ge=0.0)] = None
    currency: str | None = None


class AccountSubscription(BaseModel):
    """
    The billing state of one account. featureOverrides lets an administrator grant or revoke individual capabilities independently of the plan, which is how the 'custom' plan is fulfilled.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    accountId: str
    planId: PlanId
    status: SubscriptionStatus
    interval: BillingInterval | None = None
    features: list[FeatureId]
    """
    Resolved feature list persisted at purchase time so a catalog change never silently alters a paid account
    """
    featureOverrides: list[FeatureOverride] | None = None
    quotas: PlanQuotas
    currentPeriodStart: AwareDatetime
    currentPeriodEnd: AwareDatetime
    cancelAtPeriodEnd: bool | None = False
    payments: list[PaymentRecord] | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None
    billingModel: BillingModel | None = None
    catalogueId: str | None = None
    """
    Accepted catalogue whose terms are in force
    """
    allowances: list[MetricAllowance] | None = None
    """
    Per-metric ceilings copied from the accepted catalogue
    """
    prices: list[MetricPrice] | None = None
    """
    Per-metric unit prices copied from the accepted catalogue
    """
    spendCaps: list[SpendCap] | None = None
    """
    Caps set by the account owner or admin, not by Floweb
    """
    seatPriceMonthly: Annotated[float | None, Field(ge=0.0)] = None
    baseMonthlyPrice: Annotated[float | None, Field(ge=0.0)] = None
    anniversaryDayOfMonth: Annotated[int | None, Field(ge=1, le=31)] = None
    """
    Day the billing period rolls over and an invoice is generated
    """


class AccountEntitlements(BaseModel):
    """
    The resolved answer to 'what may this account do right now'. Sent to the UI on load and to the engine in its runtime context; both treat it as read-only.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    accountId: str
    planId: PlanId
    planName: str | None = None
    status: SubscriptionStatus
    features: list[FeatureId]
    quotas: PlanQuotas
    usage: UsageSnapshot | None = None
    credits: Annotated[int | None, Field(ge=0)] = None
    """
    Admin-granted credits available once the daily plan allowance is spent
    """
    aiEnabledByUser: bool | None = True
    """
    Account preference gating AI at runtime; AI runs only when this is true AND the matching feature is entitled
    """
    currentPeriodEnd: AwareDatetime | None = None
    billingModel: BillingModel | None = None
    metrics: list[MetricUsage] | None = None
    """
    Per-metric consumption and remaining headroom for the caller
    """
    spend: list[SpendState] | None = None
    """
    Cap state for the account and for the calling member
    """
    blocked: bool | None = False
    """
    True when a reached cap or an unpaid invoice suspends chargeable activity account-wide
    """
    blockedReason: str | None = None


class FeatureDenied(BaseModel):
    """
    Error payload returned with HTTP 402 when a gated feature is refused
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: str
    feature: FeatureId
    reason: FeatureDeniedReason
    message: str
    requiredPlan: PlanId | None = None
    currentPlan: PlanId | None = None
    metric: MeteredMetric | None = None


class Billing(BaseModel):
    """
    Per-account plans, feature entitlements, metered usage and pricing. Entitlements are the authority for whether a feature may run; plans and catalogues are only ways to assemble them. FeatureId gates a capability, MeteredMetric counts it. Field-level source of truth is floweb-server subscription.model.ts.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    subscription: AccountSubscription | None = None
    entitlements: AccountEntitlements | None = None
    catalog: PlanCatalogEntry | None = None
    catalogue: PricingCatalogue | None = None
    invoice: Invoice | None = None
    creditRequest: CreditRequest | None = None
    ticketPayload: TicketCommentPayload | None = None
