# generated by datamodel-codegen:
#   filename:  billing.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class PlanId(StrEnum):
    """
    Billing plan identifier. 'none' is an account that has not bought a plan yet and is entitled to nothing; 'custom' is assigned manually by a Floweb administrator.
    """

    none = 'none'
    basic = 'basic'
    premium = 'premium'
    max = 'max'
    custom = 'custom'


class FeatureId(StrEnum):
    """
    A gateable product capability. Every enforcement point in the server, engine and UI keys off one of these.
    """

    test_creation = 'test_creation'
    test_execution = 'test_execution'
    reporting = 'reporting'
    advanced_analytics = 'advanced_analytics'
    recorder = 'recorder'
    self_healing_basic = 'self_healing_basic'
    self_healing_ai = 'self_healing_ai'
    ai_assistant = 'ai_assistant'
    ai_test_generation = 'ai_test_generation'
    ai_vibe_testing = 'ai_vibe_testing'
    parallel_execution = 'parallel_execution'
    performance_testing = 'performance_testing'


class SubscriptionStatus(StrEnum):
    """
    Lifecycle state of an account subscription. Only 'active' and 'trialing' grant entitlements.
    """

    active = 'active'
    trialing = 'trialing'
    past_due = 'past_due'
    cancelled = 'cancelled'


class PaymentStatus(StrEnum):
    """
    Outcome of a simulated payment attempt
    """

    succeeded = 'succeeded'
    failed = 'failed'
    refunded = 'refunded'


class BillingInterval(StrEnum):
    """
    Billing cadence for a plan price
    """

    monthly = 'monthly'
    yearly = 'yearly'


class PlanQuotas(BaseModel):
    """
    Numeric limits attached to a plan. A null value means unlimited.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    executionsPerDay: Annotated[int | None, Field(ge=0)]
    maxTests: Annotated[int | None, Field(ge=0)] = None
    maxMembers: Annotated[int | None, Field(ge=0)] = None


class PlanCatalogEntry(BaseModel):
    """
    A purchasable plan as advertised on the billing page
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: PlanId
    name: Annotated[str, Field(max_length=60)]
    description: Annotated[str, Field(max_length=300)]
    priceMonthly: Annotated[float | None, Field(ge=0.0)] = None
    priceYearly: Annotated[float | None, Field(ge=0.0)] = None
    currency: str | None = 'USD'
    features: list[FeatureId]
    quotas: PlanQuotas
    highlights: list[str] | None = None
    contactOnly: bool | None = False


class PaymentRecord(BaseModel):
    """
    A simulated payment attempt retained for the billing history table. No real gateway is involved and no card data is stored.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    planId: PlanId
    amount: Annotated[float, Field(ge=0.0)]
    currency: str | None = 'USD'
    interval: BillingInterval | None = None
    status: PaymentStatus
    cardLast4: Annotated[str | None, Field(max_length=4)] = None
    reference: str | None = None
    """
    Simulated gateway reference
    """
    createdAt: AwareDatetime


class FeatureOverride(BaseModel):
    """
    An administrator-set grant or revocation of a single feature, applied on top of the plan's feature list
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    feature: FeatureId
    enabled: bool
    note: Annotated[str | None, Field(max_length=200)] = None


class UsageSnapshot(BaseModel):
    """
    Consumption for the current UTC day, used to enforce executionsPerDay
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    date: str
    """
    UTC day key, YYYY-MM-DD
    """
    executions: Annotated[int, Field(ge=0)]
    executionsLimit: Annotated[int | None, Field(ge=0)] = None
    executionsRemaining: Annotated[int | None, Field(ge=0)] = None
    creditsRemaining: Annotated[int | None, Field(ge=0)] = None
    """
    Admin-granted credits left after this execution; spent only once the plan allowance is exhausted
    """


class AccountEntitlements(BaseModel):
    """
    The resolved answer to 'what may this account do right now'. Sent to the UI on load and to the engine in its runtime context; both treat it as read-only.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    accountId: str
    planId: PlanId
    planName: str | None = None
    status: SubscriptionStatus
    features: list[FeatureId]
    quotas: PlanQuotas
    usage: UsageSnapshot | None = None
    credits: Annotated[int | None, Field(ge=0)] = None
    """
    Admin-granted credits available once the daily plan allowance is spent
    """
    aiEnabledByUser: bool | None = True
    """
    Account preference gating AI at runtime; AI runs only when this is true AND the matching feature is entitled
    """
    currentPeriodEnd: AwareDatetime | None = None


class FeatureDeniedReason(StrEnum):
    """
    Why an entitlement check failed, so callers can render the right call to action
    """

    not_in_plan = 'not_in_plan'
    quota_exceeded = 'quota_exceeded'
    subscription_inactive = 'subscription_inactive'
    disabled_by_user = 'disabled_by_user'


class FeatureDenied(BaseModel):
    """
    Error payload returned with HTTP 402 when a gated feature is refused
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: str
    feature: FeatureId
    reason: FeatureDeniedReason
    message: str
    requiredPlan: PlanId | None = None
    currentPlan: PlanId | None = None


class CreditPack(BaseModel):
    """
    A purchasable bundle of execution credits. Credits top up a plan that has a fixed allowance; pay-as-you-go plans bill usage directly and cannot use them.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: str
    credits: Annotated[int, Field(ge=1)]
    priceMinor: Annotated[int, Field(ge=0)]
    """
    Pack price in minor units of `currency`.
    """
    currency: str


class CreditPurchase(BaseModel):
    """
    Outcome of a credit top-up, carrying the new balance so the caller need not re-read it.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    packId: str
    credits: int
    amountMinor: int
    currency: str
    balance: int
    """
    Credit balance after the purchase settled.
    """
    reference: str
    createdAt: AwareDatetime


class CreditLedgerEntry(BaseModel):
    """
    One movement on an account's credit balance, positive for a grant or purchase and negative for a consumed run.
    """

    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: str
    kind: str
    amount: int
    reason: str
    createdAt: AwareDatetime


class AccountSubscription(BaseModel):
    """
    The billing state of one account. featureOverrides lets an administrator grant or revoke individual capabilities independently of the plan, which is how the 'custom' plan is fulfilled.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    accountId: str
    planId: PlanId
    status: SubscriptionStatus
    interval: BillingInterval | None = None
    features: list[FeatureId]
    """
    Resolved feature list persisted at purchase time so a catalog change never silently alters a paid account
    """
    featureOverrides: list[FeatureOverride] | None = None
    quotas: PlanQuotas
    currentPeriodStart: AwareDatetime
    currentPeriodEnd: AwareDatetime
    cancelAtPeriodEnd: bool | None = False
    payments: list[PaymentRecord] | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class Billing(BaseModel):
    """
    Per-account plans, feature entitlements and usage quotas. Entitlements are the authority for whether a feature may run; plans are only a convenient way to assemble them. Field-level source of truth is floweb-server subscription.model.ts.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    subscription: AccountSubscription | None = None
    entitlements: AccountEntitlements | None = None
    catalog: PlanCatalogEntry | None = None
