# generated by datamodel-codegen:
#   filename:  catalogue.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class PlanType(StrEnum):
    """
    How a catalogue plan meters. fixed_budget pre-buys units and counts down; payg accrues cost per unit consumed.
    """

    fixed_budget = 'fixed_budget'
    payg = 'payg'


class CatalogueRequestStatus(StrEnum):
    """
    Lifecycle of a negotiated catalogue request. 'superseded' marks a request replaced by a newer one, typically a bump-up of the plan it produced.
    """

    draft = 'draft'
    pending_review = 'pending_review'
    priced = 'priced'
    sent = 'sent'
    negotiating = 'negotiating'
    approved = 'approved'
    awaiting_payment = 'awaiting_payment'
    active = 'active'
    rejected = 'rejected'
    expired = 'expired'
    superseded = 'superseded'


class AccountPlanStatus(StrEnum):
    """
    Lifecycle of an activated plan. Only 'active' meters usage; 'scheduled' is queued behind the running plan and 'exhausted' means every fixed budget reached zero.
    """

    scheduled = 'scheduled'
    active = 'active'
    exhausted = 'exhausted'
    expired = 'expired'
    cancelled = 'cancelled'


class RevisionAuthor(StrEnum):
    """
    Which side of the negotiation authored a revision
    """

    client = 'client'
    admin = 'admin'


class CouponDiscountType(StrEnum):
    """
    How a coupon's value is applied: a percentage of the order or an absolute amount in minor units
    """

    percent = 'percent'
    fixed = 'fixed'


class UsageOutcome(StrEnum):
    """
    How a reserved unit of usage ended. Only 'completed' is charged; the other two release the hold.
    """

    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class CatalogueService(BaseModel):
    """
    A service Floweb sells, seeded from the standard catalogue and editable by an administrator. serviceId is the stable slug every plan, cap and usage reservation keys off.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    serviceId: Annotated[str, Field(max_length=60, min_length=1)]
    name: Annotated[str, Field(max_length=120)]
    description: Annotated[str, Field(max_length=500)]
    unit: Annotated[str, Field(max_length=40)]
    """
    What one unit is: 'execution', 'seat', 'GB'
    """
    listPriceMinor: Annotated[int, Field(ge=0)]
    """
    Floweb's list price per unit in minor currency units
    """
    currency: str
    active: bool


class CatalogueLine(BaseModel):
    """
    One service on a revision. name is snapshotted so a later rename of the service does not rewrite an agreed quote.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    serviceId: Annotated[str, Field(max_length=60, min_length=1)]
    name: Annotated[str, Field(max_length=120)]
    quantity: Annotated[int, Field(ge=0)]
    """
    fixed_budget: units pre-bought. payg: expected volume, used as a cap hint only.
    """
    unitPriceMinor: Annotated[int, Field(ge=0)]
    """
    Negotiated price, may differ from the service's list price
    """
    subtotalMinor: Annotated[int, Field(ge=0)]
    """
    quantity * unitPriceMinor
    """


class CatalogueRevision(BaseModel):
    """
    One immutable proposal in the negotiation thread. Revisions are appended, never edited; the highest revision number is the live offer.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    revision: Annotated[int, Field(ge=1)]
    """
    1-based, monotonic, never reused
    """
    authoredBy: RevisionAuthor
    authorId: str
    authorName: Annotated[str, Field(max_length=200)]
    lines: list[CatalogueLine]
    couponCode: Annotated[str | None, Field(max_length=40)] = None
    discountMinor: Annotated[int, Field(ge=0)]
    """
    Absolute discount resolved for this revision
    """
    subtotalMinor: Annotated[int, Field(ge=0)]
    totalMinor: Annotated[int, Field(ge=0)]
    """
    subtotalMinor - discountMinor
    """
    currency: str
    note: Annotated[str | None, Field(max_length=2000)] = None
    """
    Free-text rationale shown on the negotiation card
    """
    createdAt: AwareDatetime


class CatalogueRequest(BaseModel):
    """
    A custom plan being negotiated. The revision array is the full immutable thread from both sides; activatedAt is set once payment confirms and becomes the plan's billing anniversary.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    accountId: str
    ticketId: str | None = None
    """
    Support ticket the negotiation is conducted in
    """
    planType: PlanType
    status: CatalogueRequestStatus
    revisions: list[CatalogueRevision]
    """
    Append-only
    """
    currentRevisionId: str
    approvedByClientAt: AwareDatetime | None = None
    approvedByAdminAt: AwareDatetime | None = None
    bumpsPlanId: str | None = None
    """
    Set when this request increases the limits of an existing plan
    """
    createdAt: AwareDatetime
    activatedAt: AwareDatetime | None = None
    """
    Billing anchor once paid
    """


class PlanServiceState(BaseModel):
    """
    Per-service budget and consumption on an activated plan. budgetTotal and budgetRemaining are null on a payg plan, which is unbounded by design and constrained by caps instead.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    serviceId: Annotated[str, Field(max_length=60, min_length=1)]
    unitPriceMinor: Annotated[int, Field(ge=0)]
    budgetTotal: Annotated[int | None, Field(ge=0)]
    """
    fixed_budget: units bought
    """
    budgetRemaining: Annotated[int | None, Field(ge=0)]
    """
    fixed_budget: units left
    """
    usageCount: Annotated[int, Field(ge=0)]
    """
    Units consumed this period
    """
    usageCostMinor: Annotated[int, Field(ge=0)]
    """
    payg: cost accrued this period
    """


class Scope(StrEnum):
    account = 'account'
    user = 'user'


class UsageCap(BaseModel):
    """
    A ceiling on units consumed within one billing period. A null serviceId caps every service together; scope 'user' caps one member, scope 'account' caps the whole account.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    scope: Scope
    userId: str | None
    """
    Null when scope is 'account'
    """
    serviceId: str | None
    """
    Null applies the cap across all services
    """
    limit: Annotated[int, Field(ge=0)]


class AppliedDiscount(BaseModel):
    """
    Promo terms snapshotted at activation. Scoped to this plan for its lifetime and never inherited by a later plan; snapshotted so editing or expiring the code cannot retroactively change what an active plan is billed.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: str
    discountType: CouponDiscountType
    value: Annotated[int, Field(ge=0)]
    appliesToServiceIds: list[str]
    """
    Services the discount is limited to; empty means the whole order
    """


class AccountPlan(BaseModel):
    """
    The activated plan that meters usage. activatedAt is the billing anniversary and the anchor every period rolls forward from — deliberately not createdAt, which is when the plan was queued.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    accountId: str
    catalogueRequestId: str | None = None
    """
    Null for standard catalog plans
    """
    planType: PlanType
    status: AccountPlanStatus
    services: list[PlanServiceState]
    caps: list[UsageCap]
    activatedAt: AwareDatetime | None = None
    exhaustedAt: AwareDatetime | None = None
    appliedDiscount: AppliedDiscount | None = None
    """
    Promo terms snapshotted at activation. Scoped to this plan for its lifetime and never inherited by a later plan; snapshotted so editing or expiring the code cannot retroactively change what an active plan is billed.
    """
    currency: str
    """
    ISO-4217 code every minor-unit amount on this plan is denominated in
    """
    billingAnchorDay: Annotated[int | None, Field(ge=1, le=31)] = None
    """
    Day of month taken from activatedAt; clamped to the last day in shorter months
    """
    currentPeriodStart: AwareDatetime | None = None
    currentPeriodEnd: AwareDatetime | None = None
    autoStart: bool
    """
    Scheduled plan starts by itself when the running plan exhausts
    """
    queuedAfterPlanId: str | None = None
    createdAt: AwareDatetime


class InvoiceStatus(StrEnum):
    draft = 'draft'
    issued = 'issued'
    paid = 'paid'
    void = 'void'


class InvoiceLine(BaseModel):
    """
    One service's consumption over the invoiced period.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    serviceId: str
    name: str
    unit: str
    quantity: Annotated[int, Field(ge=0)]
    unitPriceMinor: Annotated[int, Field(ge=0)]
    subtotalMinor: Annotated[int, Field(ge=0)]


class Invoice(BaseModel):
    """
    A closed billing period rendered as a bill. Generated from an archived plan_usage_periods record, never from live counters, so it stays stable once issued.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    number: str
    """
    Human-facing reference, unique across the system
    """
    accountId: str
    planId: str
    periodKey: str
    periodStart: AwareDatetime
    periodEnd: AwareDatetime
    lines: list[InvoiceLine]
    subtotalMinor: int
    discountMinor: int
    totalMinor: int
    currency: str
    status: InvoiceStatus
    issuedAt: AwareDatetime | None = None
    dueAt: AwareDatetime | None = None
    paidAt: AwareDatetime | None = None
    createdAt: AwareDatetime


class PricingUpdateStatus(StrEnum):
    scheduled = 'scheduled'
    applied = 'applied'
    cancelled = 'cancelled'


class PricingUpdateLine(BaseModel):
    """
    One service's price move. deltaMinor is what the admin entered; the absolute prices are recorded so the change stays auditable after the catalogue moves again.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    serviceId: str
    name: str
    previousUnitPriceMinor: Annotated[int, Field(ge=0)]
    newUnitPriceMinor: Annotated[int, Field(ge=0)]
    deltaMinor: int


class PricingUpdate(BaseModel):
    """
    An admin-announced change to per-service catalogue pricing. Active PAYG plans adopt it at their first period roll on or after effectiveFrom, so usage already incurred is never repriced. Fixed-budget plans are pre-paid and never adopt it.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    status: PricingUpdateStatus
    lines: list[PricingUpdateLine]
    currency: str
    note: str | None = None
    """
    Announcement shown to affected clients
    """
    effectiveFrom: AwareDatetime
    announcedAt: AwareDatetime | None = None
    createdByEmail: str | None = None
    createdAt: AwareDatetime


class Coupon(BaseModel):
    """
    A discount applicable to a standard plan purchase or a negotiated catalogue. An empty appliesToServiceIds discounts the whole order.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Annotated[str, Field(max_length=40, min_length=1)]
    """
    Uppercase, unique
    """
    discountType: CouponDiscountType
    value: Annotated[int, Field(ge=1)]
    """
    percent: 1-100. fixed: minor units
    """
    currency: str | None = None
    """
    Set for a fixed discount only
    """
    appliesToServiceIds: list[str]
    maxRedemptions: Annotated[int | None, Field(ge=1)] = None
    redemptions: Annotated[int, Field(ge=0)]
    expiresAt: AwareDatetime | None = None
    active: bool


class Reason(Enum):
    unknown_code = 'unknown_code'
    inactive = 'inactive'
    expired = 'expired'
    fully_redeemed = 'fully_redeemed'
    not_applicable = 'not_applicable'
    currency_mismatch = 'currency_mismatch'
    NoneType_None = None


class CouponValidation(BaseModel):
    """
    Result of checking a coupon against an order. reason explains a refusal so the UI can say why rather than just greying the field.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    valid: bool
    code: str
    discountMinor: Annotated[int, Field(ge=0)]
    reason: Reason | None = None


class PlanUsageSnapshot(BaseModel):
    """
    Consumption of one service on one plan after a usage reservation settled. Distinct from billing.json's UsageSnapshot, which reports the standard plan's daily execution counter.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    planId: str
    planType: PlanType
    status: AccountPlanStatus
    serviceId: str
    outcome: UsageOutcome
    charged: bool
    """
    False when the hold was released instead of committed
    """
    budgetRemaining: Annotated[int | None, Field(ge=0)]
    usageCount: Annotated[int, Field(ge=0)]
    usageCostMinor: Annotated[int, Field(ge=0)]


class Catalogue(BaseModel):
    """
    Negotiated custom plans: the services Floweb sells, the immutable revision thread a price is agreed over, and the activated plan that meters usage against it. Standard off-the-shelf plans stay in billing.json; a catalogue plan is the bespoke alternative. Field-level source of truth is floweb-server catalogue.model.ts.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    service: CatalogueService | None = None
    request: CatalogueRequest | None = None
    plan: AccountPlan | None = None
    coupon: Coupon | None = None
