# generated by datamodel-codegen:
#   filename:  collab-protocol.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


class CollabUser(BaseModel):
    """
    A participant in a collab room
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: str
    color: str
    """
    Hex color, e.g. #3b82f6
    """
    nodeId: str | None
    """
    Currently focused node, or null
    """


class Type(StrEnum):
    add_node = 'add_node'
    update_node = 'update_node'
    delete_node = 'delete_node'
    add_edge = 'add_edge'
    delete_edge = 'delete_edge'
    add_variable = 'add_variable'
    update_variable = 'update_variable'
    delete_variable = 'delete_variable'
    add_parameter = 'add_parameter'
    update_parameter = 'update_parameter'
    delete_parameter = 'delete_parameter'


class CollabOp(BaseModel):
    """
    A single collaborative edit operation. Discriminated by `type`; payload fields (node/edge/variable/patch) are opaque and relayed unvalidated.
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    type: Type


class CollabAuth(BaseModel):
    """
    client->server: first message; authenticates the socket (5s timeout)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['auth']
    token: str
    """
    JWT access token
    """


class CollabCursorClient(BaseModel):
    """
    client->server: cursor selection and/or pointer position
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['cursor']
    nodeId: str | None = None
    x: float | None = None
    y: float | None = None
    selectedNodes: list[str] | None = None


class CollabChangeClient(BaseModel):
    """
    client->server: a batch of edit operations
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['change']
    ops: list[CollabOp]


class CollabCursorHide(BaseModel):
    """
    client->server: hide this user's cursor
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['cursor_hide']


class CollabSnapshotClient(BaseModel):
    """
    client->server: room leader sends current state to a newly joined peer
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['snapshot']
    to: str
    """
    Target userId
    """
    state: dict[str, Any]
    """
    Opaque snapshot of nodes/edges/variables/parameters
    """


class CollabTypingClient(BaseModel):
    """
    client->server: user is editing a node (nodeId null on blur)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['typing']
    nodeId: str | None = None


class CollabPing(BaseModel):
    """
    client->server: keepalive (every 25s)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['ping']


class CollabPresence(BaseModel):
    """
    server->client: full roster sent on join
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['presence']
    users: list[CollabUser]


class User(BaseModel):
    """
    The joiner (no nodeId on this object)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: str
    color: str


class CollabUserJoined(BaseModel):
    """
    server->client: broadcast when a peer joins
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['user_joined']
    user: User
    """
    The joiner (no nodeId on this object)
    """
    users: list[CollabUser]


class CollabUserLeft(BaseModel):
    """
    server->client: broadcast when a peer leaves
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['user_left']
    userId: str
    userName: str
    users: list[CollabUser]


class CollabCursorServer(BaseModel):
    """
    server->client: relayed cursor with sender identity
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['cursor']
    userId: str
    userName: str
    userColor: str
    nodeId: str | None
    x: float | None
    y: float | None
    selectedNodes: list[str]


class CollabChangeServer(BaseModel):
    """
    server->client: relayed change with sender and room version
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['change']
    ops: list[CollabOp]
    userId: str
    version: int
    """
    Monotonic room version
    """


class CollabSnapshotServer(BaseModel):
    """
    server->client: snapshot delivered to the target peer
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['snapshot']
    state: dict[str, Any]
    version: int


class CollabTypingServer(BaseModel):
    """
    server->client: relayed typing indicator with sender identity
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['typing']
    userId: str
    userName: str
    userColor: str
    nodeId: str | None


class CollabPong(BaseModel):
    """
    server->client: reply to ping
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Literal['pong']


class CollaborationProtocol(BaseModel):
    """
    WebSocket protocol for real-time flow collaboration (ws /ws/collab/:testId). Field names are camelCase; message `type` discriminators are snake_case. Messages are asymmetric: server relays enrich client messages with sender identity. Op/node/edge/state payloads are opaque pass-throughs.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    clientMessage: (
        CollabAuth
        | CollabCursorClient
        | CollabChangeClient
        | CollabCursorHide
        | CollabSnapshotClient
        | CollabTypingClient
        | CollabPing
        | None
    ) = None
    """
    Any message a client may send
    """
    serverMessage: (
        CollabPresence
        | CollabUserJoined
        | CollabUserLeft
        | CollabCursorServer
        | CollabChangeServer
        | CollabSnapshotServer
        | CollabTypingServer
        | CollabPong
        | None
    ) = None
    """
    Any message the server may send
    """
