# generated by datamodel-codegen:
#   filename:  data-lab.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import action_types, ai_contracts


class DatasetType(StrEnum):
    """
    Kind of generated dataset item
    """

    test_scenario = 'test-scenario'
    xpath_selector = 'xpath-selector'


class DataLabGenerationMode(StrEnum):
    """
    How items are generated (anything else falls back to hybrid)
    """

    ai = 'ai'
    synthetic = 'synthetic'
    hybrid = 'hybrid'


class GenerateTestsRequest(BaseModel):
    """
    POST /data-lab/generate-tests body (all fields optional; server applies defaults)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    prompt: str | None = ''
    batchSize: Annotated[int | None, Field(ge=1, le=40)] = 5
    minActions: Annotated[int | None, Field(ge=3, le=18)] = 5
    maxActions: Annotated[int | None, Field(ge=4, le=24)] = 12
    includeAdvancedActions: bool | None = True
    allowNearDuplicates: bool | None = False
    generationMode: DataLabGenerationMode | None = None
    provider: ai_contracts.AIProviderConfig | None = None


class GenerateXPathRequest(BaseModel):
    """
    POST /data-lab/generate-xpath body
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    prompt: str | None = ''
    batchSize: Annotated[int | None, Field(ge=1, le=40)] = 5
    allowNearDuplicates: bool | None = False
    generationMode: DataLabGenerationMode | None = None
    provider: ai_contracts.AIProviderConfig | None = None


class GenerateXPathFromSnippetRequest(BaseModel):
    """
    POST /data-lab/generate-xpath-from-snippet body
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    domSnippet: str
    """
    Required; DOM to derive selectors from
    """
    targetInstruction: str
    """
    Required; what to select
    """
    contextHint: str | None = ''
    allowNearDuplicates: bool | None = False
    generationMode: DataLabGenerationMode | None = None
    provider: ai_contracts.AIProviderConfig | None = None


class DatasetItemResponse(BaseModel):
    """
    A generated dataset item (also the persisted on-disk JSON shape). prompt/output/metadata shapes are discriminated by datasetType.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    datasetType: DatasetType
    createdAt: AwareDatetime
    signature: str
    """
    20-char sha256 hex slice
    """
    prompt: dict[str, Any]
    output: dict[str, Any]
    metadata: dict[str, Any]
    fileName: str
    relativePath: str


class Totals(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    generated: Annotated[int, Field(ge=0)]
    duplicatesSkipped: Annotated[int, Field(ge=0)]


class DatasetBatchResponse(BaseModel):
    """
    Response for all three generate endpoints
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    outputDir: str
    generatedCount: Annotated[int, Field(ge=0)]
    duplicatesSkipped: Annotated[int, Field(ge=0)]
    totals: Totals
    items: list[DatasetItemResponse]


class DatasetManifestItem(BaseModel):
    """
    A recent dataset entry in the status manifest
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    fileName: str
    relativePath: str
    signature: str
    createdAt: AwareDatetime
    label: str


class DataLabKindStatus(BaseModel):
    """
    Per-kind status counters. actionCoverage is present only for the tests kind.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    generated: Annotated[int, Field(ge=0)]
    duplicatesSkipped: Annotated[int, Field(ge=0)]
    uniqueSignatures: Annotated[int, Field(ge=0)]
    actionCoverage: dict[str, int] | None = None
    recent: list[DatasetManifestItem]


class DataLabStatusResponse(BaseModel):
    """
    GET /data-lab/status response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    outputDir: str
    tests: DataLabKindStatus
    xpath: DataLabKindStatus


class Type(StrEnum):
    xpath = 'xpath'
    css = 'css'


class UniquenessEstimate(StrEnum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class SelectorCandidate(BaseModel):
    """
    A candidate selector inside an xpath-selector item's output
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Type
    value: str
    robustness: Annotated[float, Field(ge=0.0, le=100.0)]
    uniquenessEstimate: UniquenessEstimate
    reason: str


class GeneratedActionObject(BaseModel):
    """
    A synthesized action inside a test-scenario item's output
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    action-<n>
    """
    type: action_types.ActionType
    label: str
    config: dict[str, Any]
    rationale: str


class DataLab(BaseModel):
    """
    Data-generation-lab API contracts (floweb-server data-lab module). camelCase throughout; persistence is file-based JSON. Generated dataset items are discriminated by datasetType; their prompt/output/metadata bodies are open objects.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    generateTestsRequest: GenerateTestsRequest | None = None
    batchResponse: DatasetBatchResponse | None = None
    statusResponse: DataLabStatusResponse | None = None
