# generated by datamodel-codegen:
#   filename:  environment.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class DateFormatPreset(StrEnum):
    """
    Named output format for a `date` variable. `custom` defers to the variable's dateFormatPattern.
    """

    iso = 'iso'
    iso_datetime = 'iso-datetime'
    rfc3339 = 'rfc3339'
    date_slash_dmy = 'date-slash-dmy'
    date_slash_mdy = 'date-slash-mdy'
    date_dash_ymd = 'date-dash-ymd'
    date_medium = 'date-medium'
    date_long = 'date-long'
    datetime_friendly = 'datetime-friendly'
    time_24h = 'time-24h'
    unix_seconds = 'unix-seconds'
    unix_millis = 'unix-millis'
    custom = 'custom'


class Type(StrEnum):
    """
    Data type of the variable
    """

    string = 'string'
    number = 'number'
    boolean = 'boolean'
    object = 'object'
    array = 'array'
    url = 'url'
    file = 'file'
    json = 'json'
    web_identifier = 'web-identifier'
    image = 'image'
    secret = 'secret'
    date = 'date'
    code = 'code'
    email = 'email'


class GlobalVariable(BaseModel):
    """
    A global variable available across all environments
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(max_length=50, min_length=1, pattern='^[a-zA-Z0-9_-]+$')]
    """
    Unique identifier for the global variable
    """
    name: Annotated[
        str, Field(max_length=50, min_length=1, pattern='^[a-zA-Z_][a-zA-Z0-9_-]*$')
    ]
    """
    Variable name used in flows
    """
    type: Type
    """
    Data type of the variable
    """
    value: Any
    """
    The variable's value; any JSON value is allowed (2026-07 decision: runtime stores structured values, aligned with TS JsonValue rather than the old string-only contract)
    """
    dateFormat: Annotated[str | None, Field(max_length=40)] = None
    """
    Output format applied when a `date` variable is substituted into an action. The stored value stays canonical ISO-8601; this only affects rendering. Either a DateFormatPreset id or, when set to `custom`, the pattern in `dateFormatPattern`. Ignored for other types.
    """
    dateFormatPattern: Annotated[str | None, Field(max_length=80)] = None
    """
    Token pattern used when `dateFormat` is `custom`, e.g. `DD MMM YYYY HH:mm`.
    """
    description: Annotated[str | None, Field(max_length=500)] = None
    """
    Description of the variable's purpose
    """
    secret: bool | None = False
    """
    When true, the value is a secret: write-only for UI clients (masked in API responses, never returned as plaintext), redacted from reports and logs, and sent in plaintext only to the engine runtime context. Set automatically when type is `secret`.
    """
    createdAt: AwareDatetime | None = None
    """
    ISO 8601 timestamp when the variable was created
    """
    updatedAt: AwareDatetime | None = None
    """
    ISO 8601 timestamp when the variable was last updated
    """


class Variable(BaseModel):
    """
    A variable (environment, global, or flow parameter). Field constraints are strict; `value` accepts any JSON value.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(max_length=50, min_length=1, pattern='^[a-zA-Z0-9_-]+$')]
    """
    Unique identifier for the variable
    """
    name: Annotated[
        str, Field(max_length=50, min_length=1, pattern='^[a-zA-Z_][a-zA-Z0-9_-]*$')
    ]
    """
    Variable name used in flows
    """
    type: Type
    """
    Data type of the variable
    """
    value: Any
    """
    The variable's value; any JSON value is allowed (2026-07 decision: runtime stores structured values, aligned with TS JsonValue rather than the old string-only contract)
    """
    dateFormat: Annotated[str | None, Field(max_length=40)] = None
    """
    Output format applied when a `date` variable is substituted into an action. The stored value stays canonical ISO-8601; this only affects rendering. Either a DateFormatPreset id or, when set to `custom`, the pattern in `dateFormatPattern`. Ignored for other types.
    """
    dateFormatPattern: Annotated[str | None, Field(max_length=80)] = None
    """
    Token pattern used when `dateFormat` is `custom`, e.g. `DD MMM YYYY HH:mm`.
    """
    description: Annotated[str | None, Field(max_length=500)] = None
    """
    Description of the variable's purpose
    """
    isOutput: bool | None = None
    """
    Whether this is an output variable (flow parameters)
    """
    secret: bool | None = False
    """
    When true, the value is a secret: write-only for UI clients (masked in API responses, never returned as plaintext), redacted from reports and logs, and sent in plaintext only to the engine runtime context. Set automatically when type is `secret`.
    """


class Environment(BaseModel):
    """
    An environment configuration with its variables. Unifies the standalone-entity and embedded-in-flow forms: only id+name are required so embedded partial environments validate; the server always sets the remaining fields on stored environments.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Annotated[str, Field(max_length=50, min_length=1, pattern='^[a-zA-Z0-9_-]+$')]
    """
    Unique identifier for the environment
    """
    name: Annotated[str, Field(max_length=100, min_length=1)]
    """
    Display name for the environment
    """
    description: Annotated[str | None, Field(max_length=500)] = None
    """
    Description of the environment's purpose
    """
    variables: Annotated[list[Variable] | None, Field(min_length=0)] = None
    """
    Environment-specific variables
    """
    isDefault: bool | None = False
    """
    Whether this is the default environment
    """
    isActive: bool | None = None
    """
    Whether this environment is currently active
    """
    createdAt: AwareDatetime | None = None
    """
    ISO 8601 timestamp when the environment was created
    """
    updatedAt: AwareDatetime | None = None
    """
    ISO 8601 timestamp when the environment was last updated
    """


class EnvironmentAndGlobalVariablesConfiguration(BaseModel):
    """
    Schema for environment configurations and global variables used in Floweb automation flows
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    environments: Annotated[list[Environment], Field(min_length=0)]
    """
    List of available environments
    """
    globalVariables: Annotated[list[GlobalVariable], Field(min_length=0)]
    """
    List of global variables available across all environments
    """
    selectedEnvironmentId: Annotated[str | None, Field(pattern='^[a-zA-Z0-9_-]+$')] = (
        None
    )
    """
    ID of the currently selected environment
    """
