# generated by datamodel-codegen:
#   filename:  flow.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from . import environment as environment_1
from . import websocket_communication


class Type(StrEnum):
    """
    Type of the flow
    """

    flow = 'flow'
    test = 'test'
    performance = 'performance'


class LastResult(StrEnum):
    """
    Result of last execution
    """

    passed = 'passed'
    failed = 'failed'
    pending = 'pending'
    running = 'running'


class AssistantAuditOperation(BaseModel):
    """
    A single tool operation performed by the AI assistant
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    tool: str
    """
    Tool name that was invoked
    """
    summary: str | None = None
    """
    Human-readable summary of the operation
    """
    payload: dict[str, Any] | None = None
    """
    Tool invocation payload
    """


class AssistantAuditEntry(BaseModel):
    """
    Audit record of an AI-assistant edit applied to the flow
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Unique audit entry identifier
    """
    createdAt: str
    """
    Timestamp when the entry was recorded
    """
    instruction: str
    """
    User instruction that triggered the assistant
    """
    message: str | None = None
    """
    Assistant response message
    """
    provider: str | None = None
    """
    LLM provider used
    """
    model: str | None = None
    """
    LLM model used
    """
    source: str | None = None
    """
    Origin of the assistant invocation
    """
    changes: list[str] | None = None
    """
    Summaries of changes applied
    """
    operations: list[AssistantAuditOperation]
    """
    Tool operations performed
    """


class Position(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x: float
    """
    X coordinate
    """
    y: float
    """
    Y coordinate
    """


class ActionData(BaseModel):
    """
    Authored content of an action node. Run state (status, message, screenshot) is deliberately absent: it is ephemeral engine/UI state and must never be persisted onto the saved document.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    label: str
    """
    Human-readable label
    """
    type: str
    """
    Action type identifier
    """
    config: dict[str, Any]
    """
    Action-specific configuration
    """
    image: str | None = None
    """
    Screenshot or icon associated with the action
    """
    expanded: bool | None = None
    """
    Whether the node is expanded in the canvas UI
    """
    description: str | None = None
    """
    Human-readable description of the action (carried on generated/AI nodes)
    """


class Action(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Unique action identifier
    """
    type: str
    """
    Action type
    """
    position: Position
    data: ActionData
    draggable: bool | None = True
    """
    React Flow canvas node option
    """
    selectable: bool | None = True
    """
    React Flow canvas node option
    """
    deletable: bool | None = True
    """
    React Flow canvas node option
    """
    selected: bool | None = False
    """
    React Flow canvas node option
    """


class Edge(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Unique edge identifier
    """
    source: str
    """
    Source action ID
    """
    sourceHandle: str | None = None
    """
    Source handle identifier (null when attached to the default handle)
    """
    target: str
    """
    Target action ID
    """
    targetHandle: str | None = None
    """
    Target handle identifier (null when attached to the default handle)
    """
    type: str | None = 'step'
    """
    Edge type
    """
    data: dict[str, Any] | None = None
    """
    Additional edge data
    """


class Zoom(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x: float
    """
    Pan X position
    """
    y: float
    """
    Pan Y position
    """
    zoom: float
    """
    Zoom level
    """


class FlowVariables(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    input: list[environment_1.Variable]
    """
    Input variables
    """
    output: list[environment_1.Variable]
    """
    Output variables
    """


class FlowParameters(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    input: list[environment_1.Variable]
    """
    Input parameters
    """
    output: list[environment_1.Variable]
    """
    Output parameters
    """
    parameterBefore: Annotated[
        list[environment_1.Variable] | None, Field(default_factory=list)
    ]
    """
    Parameters to be set before execution
    """
    variableBefore: Annotated[
        list[environment_1.Variable] | None, Field(default_factory=list)
    ]
    """
    Variables to be set before execution
    """


class Flow(BaseModel):
    """
    Complete flow definition for automation workflows
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Unique identifier for the flow
    """
    name: str
    """
    Human-readable name of the flow
    """
    description: str | None = None
    """
    Optional description of the flow
    """
    tags: list[str] | None = None
    """
    Tags for categorization and filtering
    """
    parentID: str | None = None
    """
    Parent folder ID for organization
    """
    type: Type | None = 'flow'
    """
    Type of the flow
    """
    actions: list[Action]
    """
    List of actions in the flow
    """
    edges: list[Edge]
    """
    Connections between actions
    """
    zoom: Zoom | None = None
    """
    Canvas zoom and pan state
    """
    createdAt: AwareDatetime | None = None
    """
    Creation timestamp
    """
    updatedAt: AwareDatetime | None = None
    """
    Last update timestamp
    """
    variables: FlowVariables | None = None
    """
    Flow input and output variables
    """
    parameters: FlowParameters | None = None
    """
    Flow parameters for configuration
    """
    environment: environment_1.Environment | None = None
    """
    Environment configuration
    """
    mobileSession: websocket_communication.MobileRunConfig | None = None
    """
    Persisted mobile device/app target for this test (platform, device, app source). appiumServerUrl/extraCapabilities are intentionally left at their schema defaults here — those stay run-level/account-level overrides, not part of the saved test.
    """
    globalVariables: list[environment_1.GlobalVariable] | None = None
    """
    Global variables available to the flow
    """
    synced: bool | None = None
    """
    Whether the flow is synced with server
    """
    lastRun: AwareDatetime | None = None
    """
    Last execution timestamp
    """
    lastResult: LastResult | None = None
    """
    Result of last execution
    """
    assistantAuditHistory: list[AssistantAuditEntry] | None = None
    """
    History of AI-assistant edits applied to this flow
    """
