# generated by datamodel-codegen:
#   filename:  openapi-import.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import flow as flow_1


class OpenApiVariableTarget(StrEnum):
    """
    Where generated variables (auth token, base URL, response outputs) are stored
    """

    variable = 'variable'
    parameter = 'parameter'
    environment = 'environment'
    global_ = 'global'


class OpenApiAuthKind(StrEnum):
    """
    Auth scheme inferred from the spec's security requirements
    """

    bearer = 'bearer'
    basic = 'basic'
    apiKeyQuery = 'apiKeyQuery'
    apiKeyHeader = 'apiKeyHeader'
    none = 'none'


class GroupBy(StrEnum):
    tag = 'tag'
    operation = 'operation'


class OpenApiImportRequest(BaseModel):
    """
    POST /api/openapi/:accountId/import request
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    spec: str
    """
    The OpenAPI/Swagger document as JSON or YAML text
    """
    baseUrl: str | None = ''
    includeTags: list[str] | None = []
    includeMethods: list[str] | None = []
    groupBy: GroupBy | None = 'tag'
    variableTarget: OpenApiVariableTarget | None = 'variable'
    generateAssertions: bool | None = True
    folderId: str | None = None
    persist: bool | None = False
    commitAccountVariables: bool | None = False
    """
    Create environment/global variables now even on a preview (persist=false) append. Gated separately from persist because an append still needs its referenced variables to exist.
    """


class OpenApiGeneratedVariable(BaseModel):
    """
    A variable placeholder generated for an auth token, base URL, or operation output
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    id: str
    name: str
    type: str
    description: str
    defaultValue: str
    value: str


class OpenApiSkippedOperation(BaseModel):
    """
    An operation the parser could not express as a step
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    method: str
    path: str
    reason: str


class Variables(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    input: list[OpenApiGeneratedVariable]
    output: list[OpenApiGeneratedVariable]


class Parameters(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    input: list[OpenApiGeneratedVariable]
    output: list[OpenApiGeneratedVariable]


class Zoom(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x: float
    y: float
    zoom: float


class Flow(BaseModel):
    """
    A Flow payload, keyed `actions` (not `nodes`) to match the persisted Flow contract
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    actions: list[flow_1.Action]
    edges: list[flow_1.Edge]
    variables: Variables
    parameters: Parameters
    zoom: Zoom


class OpenApiGeneratedFlow(BaseModel):
    """
    One generated test, ready to persist or preview
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    description: str
    operationCount: Annotated[int, Field(ge=0)]
    flow: Flow
    """
    A Flow payload, keyed `actions` (not `nodes`) to match the persisted Flow contract
    """
    testId: str | None


class OpenApiImportResponse(BaseModel):
    """
    POST /api/openapi/:accountId/import response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: str
    specVersion: str
    baseUrl: str
    authKind: OpenApiAuthKind
    variableTarget: OpenApiVariableTarget
    operationCount: Annotated[int, Field(ge=0)]
    flows: list[OpenApiGeneratedFlow]
    variables: list[OpenApiGeneratedVariable]
    skipped: list[OpenApiSkippedOperation]
    warnings: list[str]


class OpenAPIImport(BaseModel):
    """
    Contracts for turning an OpenAPI/Swagger document into runnable apiCall flows (floweb-server's openapi module). Field-level source of truth is floweb-server's openapi.controller.ts/service.ts/parser.ts/generator.ts.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    importRequest: OpenApiImportRequest | None = None
    importResponse: OpenApiImportResponse | None = None
