# generated by datamodel-codegen:
#   filename:  openapi-import.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class OpenApiAuthKind(StrEnum):
    """
    How generated requests authenticate, derived from the spec's security schemes
    """

    none = 'none'
    bearer = 'bearer'
    basic = 'basic'
    apiKeyHeader = 'apiKeyHeader'
    apiKeyQuery = 'apiKeyQuery'


class GroupBy(StrEnum):
    """
    'tag' produces one flow per spec tag containing its operations; 'operation' produces one flow per operation.
    """

    tag = 'tag'
    operation = 'operation'


class OpenApiImportRequest(BaseModel):
    """
    POST /openapi/import request. Supply the document inline via `spec`; the server does not fetch remote URLs on the caller's behalf.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    spec: Annotated[str, Field(min_length=2)]
    """
    The OpenAPI/Swagger document as JSON or YAML text
    """
    baseUrl: str | None = ''
    """
    Overrides the server URL taken from the spec. Useful when the spec points at production and the tests should hit staging.
    """
    includeTags: list[str] | None = []
    """
    When non-empty, only operations carrying one of these tags are imported
    """
    includeMethods: list[str] | None = []
    """
    When non-empty, only these HTTP methods are imported (case-insensitive)
    """
    groupBy: GroupBy | None = 'tag'
    """
    'tag' produces one flow per spec tag containing its operations; 'operation' produces one flow per operation.
    """
    generateAssertions: bool | None = True
    """
    Derive response assertions from each operation's declared success response
    """
    folderId: str | None = None
    """
    Folder the generated tests are created in
    """
    persist: bool | None = False
    """
    When true the generated flows are saved as tests; when false they are returned for preview only
    """


class OpenApiSkippedOperation(BaseModel):
    """
    An operation the importer chose not to generate, and why. Surfaced so a short import is explainable rather than looking like operations silently vanished.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    method: str
    path: str
    reason: str
    """
    Why this operation was skipped
    """


class OpenApiGeneratedFlow(BaseModel):
    """
    One generated flow. `flow` is a Flow graph whose nodes are apiCall actions; `testId` is set only when the import persisted it.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    description: str | None = ''
    operationCount: Annotated[int, Field(ge=0)]
    flow: dict[str, Any]
    """
    Flow graph: { nodes, edges, variables, parameters }
    """
    testId: str | None = None


class OpenApiImportResponse(BaseModel):
    """
    POST /openapi/import response
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    title: str
    """
    Spec title, used to name the generated group
    """
    specVersion: str
    """
    Spec version string as declared by the document
    """
    baseUrl: str
    """
    Resolved base URL the generated requests target
    """
    authKind: OpenApiAuthKind
    operationCount: Annotated[int, Field(ge=0)]
    """
    Operations that produced an action
    """
    flows: list[OpenApiGeneratedFlow]
    variables: list[dict[str, Any]] | None = []
    """
    Typed placeholders the generated steps reference (auth token, path parameters)
    """
    skipped: Annotated[
        list[OpenApiSkippedOperation] | None, Field(validate_default=True)
    ] = []
    warnings: list[str] | None = []


class OpenAPIImport(BaseModel):
    """
    Contracts for turning an OpenAPI 3 / Swagger 2 document into runnable apiCall flows. Parsing is deterministic (no LLM): each spec operation becomes one apiCall action whose config is an ApiCallConfig from action-configs.json, with assertions derived from the operation's declared responses.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    request: OpenApiImportRequest | None = None
    response: OpenApiImportResponse | None = None
