# generated by datamodel-codegen:
#   filename:  parallel-execution.json
#   timestamp: 2026-02-04T17:10:20+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class Mode(StrEnum):
    """
    Execution mode
    """

    full = 'full'
    partial = 'partial'


class Flow(RootModel[Any]):
    root: Any


class Position(BaseModel):
    x: float = Field(..., description='X coordinate')
    y: float = Field(..., description='Y coordinate')


class ActionData(BaseModel):
    label: str = Field(..., description='Human-readable label')
    type: str = Field(..., description='Action type identifier')
    config: dict[str, Any] = Field(..., description='Action-specific configuration')


class Action(BaseModel):
    id: str = Field(..., description='Unique action identifier')
    type: str = Field(..., description='Action type')
    position: Position
    data: ActionData


class Edge(BaseModel):
    id: str = Field(..., description='Unique edge identifier')
    source: str = Field(..., description='Source action ID')
    source_handle: str | None = Field(
        None, alias='sourceHandle', description='Source handle identifier'
    )
    target: str = Field(..., description='Target action ID')
    target_handle: str | None = Field(
        None, alias='targetHandle', description='Target handle identifier'
    )
    type: str | None = Field('step', description='Edge type')
    data: dict[str, Any] | None = Field(None, description='Additional edge data')


class Zoom(BaseModel):
    x: float = Field(..., description='Pan X position')
    y: float = Field(..., description='Pan Y position')
    zoom: float = Field(..., description='Zoom level')


class Variable(BaseModel):
    id: str = Field(..., description='Variable identifier')
    name: str = Field(..., description='Variable name')
    type: str = Field(..., description='Variable data type')
    value: str = Field(..., description='Variable value')
    description: str | None = Field(None, description='Optional description')
    is_output: bool | None = Field(
        None, alias='isOutput', description='Whether this is an output variable'
    )


class FlowVariables(BaseModel):
    input: list[Variable] = Field(..., description='Input variables')
    output: list[Variable] = Field(..., description='Output variables')


class FlowParameters(BaseModel):
    input: list[Variable] = Field(..., description='Input parameters')
    output: list[Variable] = Field(..., description='Output parameters')


class EnvironmentVariable(BaseModel):
    id: str = Field(..., description='Variable identifier')
    name: str = Field(..., description='Variable name')
    type: str = Field(..., description='Variable data type')
    value: str = Field(..., description='Variable value')
    description: str | None = Field(None, description='Optional description')


class Environment(BaseModel):
    id: str = Field(..., description='Environment identifier')
    name: str = Field(..., description='Environment name')
    variables: list[EnvironmentVariable] = Field(
        ..., description='Environment variables'
    )
    description: str | None = Field(None, description='Environment description')
    is_default: bool | None = Field(
        None, alias='isDefault', description='Whether this is the default environment'
    )
    is_active: bool | None = Field(
        None, alias='isActive', description='Whether this environment is active'
    )
    created_at: AwareDatetime = Field(
        ..., alias='createdAt', description='Creation timestamp'
    )
    updated_at: AwareDatetime = Field(
        ..., alias='updatedAt', description='Last update timestamp'
    )


class GlobalVariable(BaseModel):
    id: str = Field(..., description='Variable identifier')
    name: str = Field(..., description='Variable name')
    type: str = Field(..., description='Variable data type')
    value: str = Field(..., description='Variable value')
    description: str | None = Field(None, description='Optional description')
    created_at: AwareDatetime = Field(
        ..., alias='createdAt', description='Creation timestamp'
    )
    updated_at: AwareDatetime = Field(
        ..., alias='updatedAt', description='Last update timestamp'
    )


class Status(StrEnum):
    """
    Execution status
    """

    completed = 'completed'
    error = 'error'
    stopped = 'stopped'
    running = 'running'
    pending = 'pending'


class FlowExecutionResult(BaseModel):
    """
    Result of a single test execution
    """

    flow_id: str = Field(..., description='ID of the executed flow')
    flow_name: str = Field(..., description='Name of the executed flow')
    success: bool = Field(..., description='Whether the test passed')
    status: Status = Field(..., description='Execution status')
    total_actions: int = Field(..., description='Total actions in the flow', ge=0)
    executed_actions: int = Field(..., description='Number of actions executed', ge=0)
    successful_actions: int = Field(
        ..., description='Number of successful actions', ge=0
    )
    duration_seconds: float = Field(
        ..., description='Total execution time in seconds', ge=0.0
    )
    report: dict[str, Any] = Field(..., description='Full flow report')
    error: str | None = Field(None, description='Error message if failed')
    metadata: dict[str, Any] | None = Field({}, description='Additional test metadata')


class BrowserMode(StrEnum):
    """
    Browser mode
    """

    headful = 'headful'
    headless = 'headless'


class Browser(StrEnum):
    """
    Browser to use for execution
    """

    chrome = 'chrome'
    firefox = 'firefox'
    safari = 'safari'
    edge = 'edge'


class ParallelTestsResult(BaseModel):
    """
    Result of parallel test execution
    """

    total_tests: int = Field(..., description='Total number of tests', ge=0)
    passed_tests: int = Field(..., description='Number of passed tests', ge=0)
    failed_tests: int = Field(..., description='Number of failed tests', ge=0)
    skipped_tests: int | None = Field(0, description='Number of skipped tests', ge=0)
    total_duration_seconds: float = Field(
        ..., description='Total execution time', ge=0.0
    )
    results: list[FlowExecutionResult] = Field(
        ..., description='Individual test results'
    )
    success: bool = Field(..., description='Overall success status')


class FlowExecutionRequest(BaseModel):
    """
    Request to execute a single test/flow
    """

    flow: Flow = Field(..., description='Flow to execute with all required fields')
    mode: Mode | None = Field('full', description='Execution mode')
    recording: dict[str, Any] | None = Field(
        None, description='Recording configuration'
    )
    metadata: dict[str, Any] | None = Field({}, description='Additional test metadata')


class ParallelTestsRequest(BaseModel):
    """
    Request to execute multiple tests in parallel
    """

    tests: list[FlowExecutionRequest] = Field(
        ..., description='List of tests to execute'
    )
    data: dict[str, Any] | None = Field(
        None,
        description='Shared data containing environment and globalVariables for all tests',
    )
    max_parallel: int | None = Field(
        10, description='Maximum number of parallel executions', ge=1, le=50
    )
    stop_on_failure: bool | None = Field(
        False, description='Stop all tests if one fails'
    )
    cleanup_after: bool | None = Field(
        True, description='Cleanup resources after execution'
    )
    browser_mode: BrowserMode | None = Field('headful', description='Browser mode')
    browser: Browser | None = Field(
        'chrome', description='Browser to use for execution'
    )
    incognito: bool | None = Field(
        False, description='Run tests in incognito/private mode'
    )
    max_retries: int | None = Field(
        3, description='Maximum retries for transient failures', ge=0, le=10
    )


class ParallelExecution(BaseModel):
    requests: list[ParallelTestsRequest] | None = None
    results: list[ParallelTestsResult] | None = None


class ParallelExecutionModels(BaseModel):
    """
    Schema for parallel test execution requests and results
    """

    parallel_execution: ParallelExecution | None = Field(
        None, alias='parallelExecution'
    )
