# generated by datamodel-codegen:
#   filename:  server-entities.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class UserRole(StrEnum):
    """
    Account role
    """

    owner = 'owner'
    admin = 'admin'
    member = 'member'
    viewer = 'viewer'


class MediaStorageDriver(StrEnum):
    """
    Backing store for a media item
    """

    local = 'local'
    s3 = 's3'
    r2 = 'r2'


class ReportType(StrEnum):
    """
    Kind of execution report
    """

    flow = 'flow'
    performance = 'performance'
    parallel = 'parallel'
    suite = 'suite'


class ReportStatus(StrEnum):
    """
    Execution report status (full 6-value set; note test.recentRuns persists only passed/failed/pending/running)
    """

    passed = 'passed'
    failed = 'failed'
    error = 'error'
    running = 'running'
    pending = 'pending'
    cancelled = 'cancelled'


class FlowKind(StrEnum):
    """
    Stored test kind
    """

    flow = 'flow'
    test = 'test'
    performance = 'performance'


class FlowLastResult(StrEnum):
    """
    Last execution result of a stored test
    """

    passed = 'passed'
    failed = 'failed'
    pending = 'pending'
    running = 'running'


class QuarantineReason(StrEnum):
    """
    Why a test was quarantined
    """

    flaky = 'flaky'
    manual = 'manual'


class TestQuarantine(BaseModel):
    """
    Quarantine state for a test. A quarantined test is excluded from suite runs but stays runnable on its own so a fix can be verified.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    reason: QuarantineReason
    note: Annotated[str | None, Field(max_length=2000)] = ''
    """
    Why this test was quarantined, for whoever picks it up
    """
    flakinessScore: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    """
    Flakiness score at the time of quarantine, when quarantined from analytics
    """
    quarantinedAt: AwareDatetime
    quarantinedBy: str
    """
    User ID that quarantined the test
    """


class User(BaseModel):
    """
    A user account member (wire shape; auth secrets stripped by toJSON)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: Annotated[str, Field(max_length=100)]
    email: Annotated[str, Field(max_length=254)]
    role: UserRole
    accountId: str
    isActive: bool
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class AccountSettings(BaseModel):
    """
    Per-account preferences
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    timezone: str
    dateFormat: str
    language: str


class Account(BaseModel):
    """
    A tenant account
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: Annotated[str, Field(max_length=100)]
    ownerId: str
    editLocked: bool | None = False
    settings: AccountSettings
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class AccountDataStore(BaseModel):
    """
    Decrypted per-account environments and global variables (persisted encrypted; plaintext arrays are the wire/domain shape). Elements follow environment.json Environment/GlobalVariable.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    accountId: str
    environments: list[dict[str, Any]]
    globalVariables: list[dict[str, Any]]
    updatedAt: AwareDatetime


class Folder(BaseModel):
    """
    A folder in the test tree
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: Annotated[str, Field(max_length=200)]
    accountId: str
    parentId: str | None
    path: str
    createdBy: str
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class MediaItem(BaseModel):
    """
    An uploaded media asset (storageKey stripped by toJSON; url populated at read time)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    accountId: str
    filename: str
    originalName: str
    mimeType: str
    sizeBytes: Annotated[int, Field(ge=0)]
    storageDriver: MediaStorageDriver
    storageKey: str
    """
    Server-side only; stripped before it reaches the client
    """
    url: str | None = None
    """
    Resolved access URL (read-time only)
    """
    uploadedBy: str
    createdAt: AwareDatetime


class ExecutedByType(StrEnum):
    """
    What initiated the run. An API key is the initiator of a CI run; there is no user.
    """

    user = 'user'
    api_key = 'api_key'


class ExecutionReport(BaseModel):
    """
    A stored execution report. `report` holds a FlowReport (execution-results.json), FlowExecutionResult (parallel-execution.json), or an opaque object depending on `type`.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    accountId: str
    testId: str | None = None
    flowId: str | None = None
    flowName: str | None = None
    type: ReportType
    status: ReportStatus
    duration: Annotated[float, Field(ge=0.0)]
    report: dict[str, Any]
    metadata: dict[str, Any] | None = None
    executedBy: str
    executedByType: ExecutedByType | None = 'user'
    """
    What initiated the run. An API key is the initiator of a CI run; there is no user.
    """
    executedByName: str | None = None
    executedByEmail: str | None = None
    createdAt: AwareDatetime


class TestRecentRun(BaseModel):
    """
    A recent run summary on a stored test. status uses the full ReportStatus set on the domain side; the persistence layer enforces only passed/failed/pending/running.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    status: ReportStatus
    createdAt: AwareDatetime


class StoredTestInput(BaseModel):
    """
    Payload to create/update a stored test. flowData is a Flow (flow.json) or PerformanceTest (performance-test.json).
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: Annotated[str, Field(max_length=300)]
    folderId: str | None = None
    flowData: dict[str, Any]
    type: FlowKind | None = None
    tags: list[str] | None = None


class StoredTestRecord(BaseModel):
    """
    A persisted test record
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: Annotated[str, Field(max_length=300)]
    accountId: str
    folderId: str | None
    flowData: dict[str, Any]
    type: FlowKind
    tags: list[str]
    lastResult: FlowLastResult | None = None
    quarantine: TestQuarantine | None = None
    """
    Set when the test is quarantined; null when it runs normally
    """
    createdBy: str | None = None
    updatedBy: str | None = None
    syncedAt: AwareDatetime | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class TestCatalogItem(BaseModel):
    """
    A test catalog/list projection (carries recentRuns)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: str
    folderId: str | None
    type: FlowKind
    tags: list[str]
    description: str | None = None
    status: str | None = None
    lastResult: FlowLastResult | None = None
    recentRuns: list[TestRecentRun] | None = None
    quarantine: TestQuarantine | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class EngineSession(BaseModel):
    """
    Engine handshake/JWT session payload (not persisted). issuedAt/expiresAt are epoch numbers.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    accountId: str
    userId: str
    role: UserRole
    token: str
    issuedAt: int
    expiresAt: int


class PaginatedResponse(BaseModel):
    """
    Generic pagination envelope convention. `items` is the page of results (element type varies by endpoint). Uses items/page/limit/total/hasMore.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    items: list[Any]
    page: Annotated[int, Field(ge=0)]
    limit: Annotated[int, Field(ge=0)]
    total: Annotated[int, Field(ge=0)]
    hasMore: bool


class ImageUploadResponse(BaseModel):
    """
    Response to an image upload
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    mediaId: str
    url: str
    filename: str


class ServerEntities(BaseModel):
    """
    Persisted server-side domain entities (wire shape after Mongoose toJSON: _id->id, server-only auth/storage fields stripped). Field-level source of truth is floweb-server *.model.ts. Dates are ISO strings on the wire.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    user: User | None = None
    account: Account | None = None
    folder: Folder | None = None
    media: MediaItem | None = None
    report: ExecutionReport | None = None
    test: StoredTestRecord | None = None
