# generated by datamodel-codegen:
#   filename:  suite.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class SuiteExecutionStatus(StrEnum):
    """
    Lifecycle status of a suite execution
    """

    pending = 'pending'
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'
    not_run = 'not_run'


class SuiteExecutionTestStatus(StrEnum):
    """
    Status of a single test within a suite execution
    """

    pending = 'pending'
    running = 'running'
    passed = 'passed'
    failed = 'failed'
    cancelled = 'cancelled'
    not_run = 'not_run'


class SuiteScheduleStatus(StrEnum):
    """
    Status of a scheduled suite run
    """

    scheduled = 'scheduled'
    queued = 'queued'
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'
    not_run = 'not_run'


class SuiteTriggerType(StrEnum):
    """
    What triggered a suite execution
    """

    manual = 'manual'
    scheduled = 'scheduled'


class SuiteRunConfig(BaseModel):
    """
    Run configuration for a suite. The persisted fields are browser/headless/incognito/environmentId/parallel/maxParallel/stopOnFailure (floweb-server normalizeRunConfig); recordExecution and randomBrowserPool are accepted from the client but not persisted.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    browser: str
    """
    Browser to run with
    """
    headless: bool
    """
    Run headless
    """
    incognito: bool
    """
    Run in incognito/private mode
    """
    environmentId: str | None
    """
    Environment applied to the run
    """
    parallel: bool
    """
    Run suite tests in parallel
    """
    maxParallel: Annotated[int, Field(ge=1, le=15)]
    """
    Max parallel workers (clamped 1-15 by the server)
    """
    stopOnFailure: bool
    """
    Stop the suite on first failure
    """
    recordExecution: bool | None = None
    """
    Client hint to record the run (not persisted server-side)
    """
    randomBrowserPool: list[str] | None = None
    """
    Eligible browsers when browser='random' (client-only, not persisted)
    """


class SuiteTestRef(BaseModel):
    """
    Reference to a test within a suite or schedule
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    testId: str
    """
    Referenced test id
    """
    flowName: str | None = None
    """
    Denormalized flow name
    """


class Suite(BaseModel):
    """
    A test suite definition
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Suite id (Mongoose _id mapped to id on the wire)
    """
    accountId: str
    """
    Owning account
    """
    name: Annotated[str, Field(max_length=300)]
    """
    Suite name
    """
    description: Annotated[str | None, Field(max_length=2000)] = None
    """
    Suite description
    """
    tags: list[str] | None = []
    """
    Suite tags
    """
    runConfig: SuiteRunConfig
    tests: list[SuiteTestRef]
    """
    Tests in the suite
    """
    testIds: list[str]
    """
    Ordered test ids
    """
    createdBy: str
    """
    Creator user id
    """
    updatedBy: str
    """
    Last updater user id
    """
    createdAt: AwareDatetime | None = None
    """
    Creation timestamp
    """
    updatedAt: AwareDatetime | None = None
    """
    Last update timestamp
    """


class SuiteExecutionTest(BaseModel):
    """
    Per-test record within a suite execution
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    testId: str
    """
    Referenced test id
    """
    flowName: str | None = None
    """
    Denormalized flow name
    """
    status: SuiteExecutionTestStatus
    reportId: str | None = None
    """
    Execution report id
    """
    message: str | None = None
    """
    Status message
    """
    browser: str | None = None
    """
    Browser used for this test
    """
    startedAt: AwareDatetime | None = None
    """
    Start timestamp
    """
    finishedAt: AwareDatetime | None = None
    """
    Finish timestamp
    """


class SuiteExecution(BaseModel):
    """
    A suite execution record
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Execution id
    """
    accountId: str
    """
    Owning account
    """
    suiteId: str
    """
    Suite this execution belongs to
    """
    label: Annotated[str, Field(max_length=300)]
    """
    Execution label
    """
    suiteName: str | None = None
    """
    Denormalized suite name
    """
    suiteDescription: str | None = None
    """
    Denormalized suite description
    """
    suiteTags: list[str] | None = []
    """
    Denormalized suite tags
    """
    scheduleId: str | None = None
    """
    Schedule that triggered this execution, if any
    """
    triggerType: SuiteTriggerType
    status: SuiteExecutionStatus
    runConfig: SuiteRunConfig
    testIds: list[str]
    """
    Ordered test ids
    """
    tests: list[SuiteExecutionTest]
    """
    Per-test records
    """
    skippedTestIds: list[str] | None = []
    """
    Tests excluded from this run because they were quarantined. Recorded so a short run is explainable rather than looking like tests silently vanished.
    """
    createdBy: str
    """
    Creator user id
    """
    updatedBy: str
    """
    Last updater user id
    """
    startedAt: AwareDatetime | None = None
    """
    Start timestamp
    """
    finishedAt: AwareDatetime | None = None
    """
    Finish timestamp
    """
    createdAt: AwareDatetime
    """
    Creation timestamp
    """
    updatedAt: AwareDatetime
    """
    Last update timestamp
    """


class SuiteSchedule(BaseModel):
    """
    A scheduled suite run
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    Schedule id
    """
    accountId: str
    """
    Owning account
    """
    suiteId: str
    """
    Suite this schedule targets
    """
    label: Annotated[str, Field(max_length=300)]
    """
    Schedule label
    """
    suiteName: str | None = None
    """
    Denormalized suite name
    """
    suiteDescription: str | None = None
    """
    Denormalized suite description
    """
    suiteTags: list[str] | None = []
    """
    Denormalized suite tags
    """
    status: SuiteScheduleStatus
    runAt: AwareDatetime
    """
    When the run is due
    """
    runWindowExpiresAt: AwareDatetime
    """
    When the run window expires
    """
    runConfig: SuiteRunConfig
    tests: list[SuiteTestRef]
    """
    Scheduled tests
    """
    testIds: list[str]
    """
    Ordered test ids
    """
    executionIds: list[str]
    """
    Executions spawned by this schedule
    """
    latestExecutionId: str | None = None
    """
    Most recent execution id
    """
    createdBy: str
    """
    Creator user id
    """
    updatedBy: str
    """
    Last updater user id
    """
    startedAt: AwareDatetime | None = None
    """
    Start timestamp
    """
    finishedAt: AwareDatetime | None = None
    """
    Finish timestamp
    """
    createdAt: AwareDatetime
    """
    Creation timestamp
    """
    updatedAt: AwareDatetime
    """
    Last update timestamp
    """


class SuiteModel(BaseModel):
    """
    Test suites, their scheduled runs, and execution records. Field-level source of truth is floweb-server suite.model.ts (persisted shape); dates are ISO strings on the wire.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    suite: Suite | None = None
    execution: SuiteExecution | None = None
    schedule: SuiteSchedule | None = None
