# generated by datamodel-codegen:
#   filename:  websocket-communication.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict


class WebSocketMessage(BaseModel):
    """
    Base WebSocket message structure
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: str
    """
    Command type
    """
    flow_id: str | None = None
    """
    Flow ID for the command
    """


class SessionInfo(BaseModel):
    """
    Information about an active session
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    flowId: str
    """
    Flow ID
    """
    status: str
    """
    Session status
    """
    browser: str
    """
    Browser type
    """
    flowName: str | None = None
    """
    Flow name
    """
    startedAt: int
    """
    Start timestamp
    """


class Flow(BaseModel):
    """
    Flow to execute
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: str
    actions: list[dict[str, Any]]
    edges: list[dict[str, Any]]


class Mode(StrEnum):
    full = 'full'
    partial = 'partial'


class RunCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run']
    """
    Command type
    """
    flow: Flow
    """
    Flow to execute
    """
    mode: Mode | None = 'full'
    recording: dict[str, Any] | None = None


class RecordCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['record']
    """
    Command type
    """
    flow_id: str | None = None
    """
    Flow ID for the command
    """
    url: str | None = None
    config: dict[str, Any] | None = {}


class PauseRecordingCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['pause_recording']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class ResumeRecordingCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['resume_recording']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class StopRecordingCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['stop_recording']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class FinishRecordingCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['finish_recording']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """
    flow_name: str | None = 'Recorded Flow'


class GetRecordingStatusCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_recording_status']
    """
    Command type
    """
    session_id: str | None = None


class ListRecordingsCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['list_recordings']
    """
    Command type
    """


class ConvertRecordingToFlowCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['convert_recording_to_flow']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """
    flow_name: str | None = 'Recorded Flow'


class GetRealtimeActionsCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_realtime_actions']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class GetLatestRealtimeActionCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_latest_realtime_action']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class StopCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['stop']
    """
    Command type
    """
    flow_id: str | None = None
    """
    Flow ID for the command
    """


class CloseCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['close']
    """
    Command type
    """


class ListSessionsCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['list_sessions']
    """
    Command type
    """


class CloseSessionCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['close_session']
    """
    Command type
    """
    flow_id: str | None = None
    """
    Flow ID for the command
    """


class RestartEngineCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['restart_engine']
    """
    Command type
    """


class CloseEngineCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['close_engine']
    """
    Command type
    """


class GetEngineStatusCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_engine_status']
    """
    Command type
    """


class StartPerformanceScanCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['start_performance_scan']
    """
    Command type
    """
    test_id: str
    """
    Performance test ID
    """
    url: str
    """
    URL to navigate to and record
    """


class StopPerformanceScanCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['stop_performance_scan']
    """
    Command type
    """
    test_id: str
    """
    Performance test ID
    """
    session_id: str
    """
    Recording session ID
    """


class RunLoadTestCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run_load_test']
    """
    Command type
    """
    test_id: str
    """
    Performance test ID
    """
    config: dict[str, Any]
    """
    Load test configuration
    """
    auth_config: dict[str, Any] | None = None
    """
    Authentication configuration for load test
    """


class StopLoadTestCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['stop_load_test']
    """
    Command type
    """
    test_id: str
    """
    Performance test ID
    """


class WebSocketResponse(BaseModel):
    """
    Base WebSocket response structure
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: str
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    message: str | None = None
    """
    Response message
    """


class Report(BaseModel):
    """
    Flow execution report
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    actions: list[dict[str, Any]] | None = None
    variables: dict[str, Any] | None = None
    parameters: dict[str, Any] | None = None
    output: dict[str, Any] | None = None


class RunResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run']
    """
    Command that was executed
    """
    mode: Mode
    reports: list[Report]


class ListSessionsResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['list_sessions']
    """
    Command that was executed
    """
    sessions: list[SessionInfo]


class EngineStatusResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_engine_status']
    """
    Command that was executed
    """
    status: str
    """
    Engine status
    """
    uptime: int
    """
    Engine uptime in seconds
    """
    active_sessions: int
    """
    Number of active sessions
    """


class Command(StrEnum):
    """
    Command that was executed
    """

    record = 'record'
    pause_recording = 'pause_recording'
    resume_recording = 'resume_recording'
    stop_recording = 'stop_recording'
    finish_recording = 'finish_recording'


class RecordingResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Command
    """
    Command that was executed
    """
    session_id: str | None = None
    data: dict[str, Any] | None = None


class RecordingStatusResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_recording_status']
    """
    Command that was executed
    """
    session_info: dict[str, Any] | None = None


class ListRecordingsResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['list_recordings']
    """
    Command that was executed
    """
    recordings: list[dict[str, Any]] | None = []


class DebugRunCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_run']
    """
    Command type
    """
    session_id: str
    """
    Unique debug session identifier
    """
    flow: dict[str, Any]
    """
    Flow to execute in debug mode
    """
    breakpoints: list[str] | None = []
    """
    List of action IDs where execution should pause
    """
    mode: Literal['debug'] = 'debug'


class DebugStepCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_step']
    """
    Command type
    """
    session_id: str
    """
    Debug session identifier
    """


class DebugContinueCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_continue']
    """
    Command type
    """
    session_id: str
    """
    Debug session identifier
    """


class DebugPauseCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_pause']
    """
    Command type
    """
    session_id: str
    """
    Debug session identifier
    """


class DebugStopCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_stop']
    """
    Command type
    """
    session_id: str
    """
    Debug session identifier
    """


class Command2(StrEnum):
    """
    Command that was executed
    """

    debug_run = 'debug_run'
    debug_step = 'debug_step'
    debug_continue = 'debug_continue'
    debug_pause = 'debug_pause'
    debug_stop = 'debug_stop'
    debug_error = 'debug_error'


class State(StrEnum):
    """
    Current debug session state
    """

    ready = 'ready'
    running = 'running'
    paused = 'paused'
    stepping = 'stepping'
    completed = 'completed'
    error = 'error'
    stopped = 'stopped'


class DebugResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Command2
    """
    Command that was executed
    """
    session_id: str | None = None
    """
    Debug session identifier
    """
    state: State | None = None
    """
    Current debug session state
    """
    data: dict[str, Any] | None = None
    """
    Additional debug data (action results, variables, etc.)
    """
    error: str | None = None
    """
    Error message if command failed
    """


class SuiteRunConfigWire(BaseModel):
    """
    run_suite nested run_config. Interior is camelCase (exception to the snake_case wire); the engine also accepts snake_case aliases for the parallel flags.
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    browser: str | None = None
    headless: bool | None = None
    incognito: bool | None = None
    recordExecution: bool | None = None
    environmentId: str | None = None
    randomBrowserPool: list[str] | None = None


class SuiteTestResultWire(BaseModel):
    """
    Per-test result entry in run_suite responses/progress (snake_case)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    test_id: str
    flow_name: str
    status: str
    report_id: str | None = None
    message: str | None = None


class TriggerType(StrEnum):
    manual = 'manual'
    scheduled = 'scheduled'


class RunSuiteCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run_suite']
    """
    Command type
    """
    suite_id: str
    schedule_id: str | None = None
    trigger_type: TriggerType | None = None
    label: str | None = None
    run_config: SuiteRunConfigWire | None = None
    parallel: bool | None = None
    maxParallel: int | None = None
    stopOnFailure: bool | None = None


class CancelSuiteCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['cancel_suite']
    """
    Command type
    """
    suite_id: str
    running_test_ids: list[str]


class WaitType(StrEnum):
    duration = 'duration'
    element = 'element'
    interactable = 'interactable'


class AddRecordingWaitCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['add_recording_wait']
    """
    Command type
    """
    session_id: str
    wait_type: WaitType
    duration: float | None = None
    """
    ms; default 3000, min 100
    """
    timeout: float | None = None
    """
    ms; default 10000
    """
    selector: str | None = None
    """
    Required when wait_type is element or interactable
    """
    fallback_to_duration: bool | None = True
    fallback_duration: float | None = None
    """
    ms; default 2000
    """


class AuthenticateCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['authenticate']
    """
    Command type
    """
    token: str
    account_id: str | None = None
    """
    Sent by the client but not consumed by the engine (account derived from token)
    """
    server_url: str | None = None


class Status(StrEnum):
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class RunSuiteResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run_suite']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    suite_id: str | None = None
    suite_execution_id: str | None = None
    status: Status | None = None
    total: int | None = None
    completed: int | None = None
    passed: int | None = None
    failed: int | None = None
    cancelled: int | None = None
    test_results: list[SuiteTestResultWire] | None = None
    message: str | None = None
    """
    Response message
    """
    code: str | None = None
    error: str | None = None


class CancelSuiteResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['cancel_suite']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    suite_id: str
    signalled: bool


class AddRecordingWaitResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['add_recording_wait']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    session_id: str
    wait_action: dict[str, Any] | None = None
    message: str | None = None
    """
    Response message
    """
    error: str | None = None


class Code(StrEnum):
    ENGINE_TOKEN_MISSING = 'ENGINE_TOKEN_MISSING'
    ENGINE_TOKEN_INVALID = 'ENGINE_TOKEN_INVALID'
    ENGINE_CONNECTION_REFUSED = 'ENGINE_CONNECTION_REFUSED'


class AuthenticateResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['authenticate']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    account_id: str | None = None
    message: str | None = None
    """
    Response message
    """
    code: Code | None = None


class Runtime(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    is_docker: bool | None = None
    platform: str | None = None


class ConnectedResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['connected']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    host: str
    ws_port: int
    http_port: int
    runtime: Runtime


class RunSuiteProgressResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run_suite_progress']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    suite_id: str
    suite_execution_id: str
    status: Literal['running']
    total: int
    completed: int
    passed: int
    failed: int
    cancelled: int
    running: list[str]
    current: SuiteTestResultWire | None = None


class Data(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    waitActionId: str
    triggerActionId: str
    dependentActionId: str
    dependentActionType: str
    reason: str
    confidence: float | None
    waitType: str
    duration: int
    effectiveWaitMs: int
    selector: str
    selectors: list[str]


class RecordingSmartWaitDecision(BaseModel):
    """
    engine->frontend diagnostic emitted when a smart wait is inserted during recording. Top-level is snake_case; the data sub-object is camelCase (exception to the wire convention).
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: Literal['recording_smart_wait_decision']
    command: Literal['recording_smart_wait_decision']
    action_type: Literal['smart_wait_decision']
    timestamp: int
    """
    epoch ms
    """
    session_id: str
    flow_id: str
    data: Data


class ErrorResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: str
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    message: str
    """
    Response message
    """
    error: str


class WebsocketCommunication(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    commands: (
        list[
            RunCommand
            | RecordCommand
            | PauseRecordingCommand
            | ResumeRecordingCommand
            | StopRecordingCommand
            | FinishRecordingCommand
            | GetRecordingStatusCommand
            | ListRecordingsCommand
            | ConvertRecordingToFlowCommand
            | GetRealtimeActionsCommand
            | GetLatestRealtimeActionCommand
            | StopCommand
            | CloseCommand
            | ListSessionsCommand
            | CloseSessionCommand
            | RestartEngineCommand
            | CloseEngineCommand
            | GetEngineStatusCommand
            | StartPerformanceScanCommand
            | StopPerformanceScanCommand
            | RunLoadTestCommand
            | StopLoadTestCommand
            | DebugRunCommand
            | DebugStepCommand
            | DebugContinueCommand
            | DebugPauseCommand
            | DebugStopCommand
            | RunSuiteCommand
            | CancelSuiteCommand
            | AddRecordingWaitCommand
            | AuthenticateCommand
        ]
        | None
    ) = None
    responses: (
        list[
            RunResponse
            | ListSessionsResponse
            | EngineStatusResponse
            | RecordingResponse
            | RecordingStatusResponse
            | ListRecordingsResponse
            | DebugResponse
            | WebSocketResponse
            | RunSuiteResponse
            | CancelSuiteResponse
            | AddRecordingWaitResponse
            | AuthenticateResponse
            | ConnectedResponse
            | RunSuiteProgressResponse
            | RecordingSmartWaitDecision
            | ErrorResponse
        ]
        | None
    ) = None


class WebSocketCommunicationModels(BaseModel):
    """
    Schema for WebSocket API commands and responses
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    websocketCommunication: WebsocketCommunication | None = None
