# generated by datamodel-codegen:
#   filename:  websocket-communication.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class WebSocketMessage(BaseModel):
    """
    Base WebSocket message structure
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: str
    """
    Command type
    """
    flow_id: str | None = None
    """
    Flow ID for the command
    """


class SessionInfo(BaseModel):
    """
    Information about an active session
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    flowId: str
    """
    Flow ID
    """
    status: str
    """
    Session status
    """
    browser: str
    """
    Browser type
    """
    flowName: str | None = None
    """
    Flow name
    """
    startedAt: int
    """
    Start timestamp
    """


class BrowserAdapter(StrEnum):
    """
    Browser automation adapter for web actions; omitted uses the engine default.
    """

    selenium = 'selenium'
    playwright = 'playwright'


class Flow(BaseModel):
    """
    Flow to execute
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    name: str
    actions: list[dict[str, Any]]
    edges: list[dict[str, Any]]


class Mode(StrEnum):
    full = 'full'
    partial = 'partial'


class Platform(StrEnum):
    android = 'android'
    ios = 'ios'


class MobileRunConfig(BaseModel):
    """
    Appium capabilities for a run's mobile device session. Nested (rather than flat fields on RunCommand) so a single 'mobile is None' check means 'no mobile target configured for this run'. extraCapabilities is merged last over every derived capability, which is what makes a cloud device farm (BrowserStack/Sauce/etc.) reachable without any provider-specific schema.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    platform: Platform
    automationName: str | None = None
    """
    Appium driver name; defaults to UiAutomator2 on Android and XCUITest on iOS
    """
    deviceName: str | None = ''
    udid: str | None = ''
    """
    Exact device/simulator id; takes precedence over deviceName
    """
    platformVersion: str | None = ''
    app: str | None = ''
    """
    Local path to an installed .apk/.ipa/.app, resolved by the engine from an appBinaryId: reference
    """
    appPackage: str | None = ''
    appActivity: str | None = ''
    bundleId: str | None = ''
    appiumServerUrl: str | None = 'http://127.0.0.1:4723'
    """
    Relative to the engine process, not the browser — matters when the engine runs remotely or in Docker
    """
    noReset: bool | None = True
    fullReset: bool | None = False
    autoGrantPermissions: bool | None = False
    newCommandTimeout: Annotated[int | None, Field(ge=0)] = 120
    extraCapabilities: dict[str, Any] | None = None
    """
    Raw Appium capabilities merged last, for cloud device farms or anything not modeled above
    """


class RecordCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['record']
    """
    Command type
    """
    flow_id: str | None = None
    """
    Flow ID for the command
    """
    url: str | None = None
    browserAdapter: BrowserAdapter | None = None
    """
    Browser automation adapter for the recording session; omitted uses the engine default. NOTE: this schema's RecordCommand is a documentation model only — the real wire contract is the hand-maintained RecordCommand in backend/engine/types/websocket_models.py, which must be edited to match.
    """
    config: dict[str, Any] | None = {}


class PauseRecordingCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['pause_recording']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class ResumeRecordingCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['resume_recording']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class StopRecordingCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['stop_recording']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class FinishRecordingCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['finish_recording']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """
    flow_name: str | None = 'Recorded Flow'


class GetRecordingStatusCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_recording_status']
    """
    Command type
    """
    session_id: str | None = None


class ListRecordingsCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['list_recordings']
    """
    Command type
    """


class ConvertRecordingToFlowCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['convert_recording_to_flow']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """
    flow_name: str | None = 'Recorded Flow'


class GetRealtimeActionsCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_realtime_actions']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class GetLatestRealtimeActionCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_latest_realtime_action']
    """
    Command type
    """
    session_id: str
    """
    Recording session ID
    """


class StopCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['stop']
    """
    Command type
    """
    flow_id: str | None = None
    """
    Flow ID for the command
    """


class CloseCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['close']
    """
    Command type
    """


class ListSessionsCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['list_sessions']
    """
    Command type
    """


class CloseSessionCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['close_session']
    """
    Command type
    """
    flow_id: str | None = None
    """
    Flow ID for the command
    """


class RestartEngineCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['restart_engine']
    """
    Command type
    """


class CloseEngineCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['close_engine']
    """
    Command type
    """


class GetEngineStatusCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_engine_status']
    """
    Command type
    """


class GetComponentsStatusCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_components_status']
    """
    Command type
    """


class InstallComponentCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['install_component']
    """
    Command type
    """
    component_id: str
    """
    Registry id of the engine-owned downloadable component to install
    """


class RemoveComponentCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['remove_component']
    """
    Command type
    """
    component_id: str
    """
    Registry id of the engine-owned downloadable component to remove
    """


class EnableSafaridriverCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['enable_safaridriver']
    """
    Command type
    """


class StartPerformanceScanCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['start_performance_scan']
    """
    Command type
    """
    test_id: str
    """
    Performance test ID
    """
    url: str
    """
    URL to navigate to and record
    """


class StopPerformanceScanCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['stop_performance_scan']
    """
    Command type
    """
    test_id: str
    """
    Performance test ID
    """
    session_id: str
    """
    Recording session ID
    """


class RunLoadTestCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run_load_test']
    """
    Command type
    """
    test_id: str
    """
    Performance test ID
    """
    config: dict[str, Any]
    """
    Load test configuration
    """
    auth_config: dict[str, Any] | None = None
    """
    Authentication configuration for load test
    """


class StopLoadTestCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['stop_load_test']
    """
    Command type
    """
    test_id: str
    """
    Performance test ID
    """


class WebSocketResponse(BaseModel):
    """
    Base WebSocket response structure
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: str
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    message: str | None = None
    """
    Response message
    """


class Report(BaseModel):
    """
    Flow execution report
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    actions: list[dict[str, Any]] | None = None
    variables: dict[str, Any] | None = None
    parameters: dict[str, Any] | None = None
    output: dict[str, Any] | None = None


class RunResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run']
    """
    Command that was executed
    """
    mode: Mode
    reports: list[Report]


class ListSessionsResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['list_sessions']
    """
    Command that was executed
    """
    sessions: list[SessionInfo]


class EngineStatusResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_engine_status']
    """
    Command that was executed
    """
    status: str
    """
    Engine status
    """
    uptime: int
    """
    Engine uptime in seconds
    """
    active_sessions: int
    """
    Number of active sessions
    """


class Command(StrEnum):
    """
    Command that was executed
    """

    record = 'record'
    pause_recording = 'pause_recording'
    resume_recording = 'resume_recording'
    stop_recording = 'stop_recording'
    finish_recording = 'finish_recording'


class RecordingResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Command
    """
    Command that was executed
    """
    session_id: str | None = None
    data: dict[str, Any] | None = None


class RecordingStatusResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['get_recording_status']
    """
    Command that was executed
    """
    session_info: dict[str, Any] | None = None


class ListRecordingsResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['list_recordings']
    """
    Command that was executed
    """
    recordings: list[dict[str, Any]] | None = []


class DebugRunCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_run']
    """
    Command type
    """
    session_id: str
    """
    Unique debug session identifier
    """
    flow: dict[str, Any]
    """
    Flow to execute in debug mode
    """
    breakpoints: list[str] | None = []
    """
    List of action IDs where execution should pause
    """
    mode: Literal['debug'] = 'debug'


class DebugStepCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_step']
    """
    Command type
    """
    session_id: str
    """
    Debug session identifier
    """


class DebugContinueCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_continue']
    """
    Command type
    """
    session_id: str
    """
    Debug session identifier
    """


class DebugPauseCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_pause']
    """
    Command type
    """
    session_id: str
    """
    Debug session identifier
    """


class DebugStopCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['debug_stop']
    """
    Command type
    """
    session_id: str
    """
    Debug session identifier
    """


class Command2(StrEnum):
    """
    Command that was executed
    """

    debug_run = 'debug_run'
    debug_step = 'debug_step'
    debug_continue = 'debug_continue'
    debug_pause = 'debug_pause'
    debug_stop = 'debug_stop'
    debug_error = 'debug_error'


class State(StrEnum):
    """
    Current debug session state
    """

    ready = 'ready'
    running = 'running'
    paused = 'paused'
    stepping = 'stepping'
    completed = 'completed'
    error = 'error'
    stopped = 'stopped'


class DebugResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Command2
    """
    Command that was executed
    """
    session_id: str | None = None
    """
    Debug session identifier
    """
    state: State | None = None
    """
    Current debug session state
    """
    data: dict[str, Any] | None = None
    """
    Additional debug data (action results, variables, etc.)
    """
    error: str | None = None
    """
    Error message if command failed
    """


class SuiteRunConfigWire(BaseModel):
    """
    run_suite nested run_config. Interior is camelCase (exception to the snake_case wire); the engine also accepts snake_case aliases for the parallel flags.
    """

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    browser: str | None = None
    headless: bool | None = None
    incognito: bool | None = None
    browserAdapter: BrowserAdapter | None = None
    recordExecution: bool | None = None
    environmentId: str | None = None
    randomBrowserPool: list[str] | None = None


class SuiteTestResultWire(BaseModel):
    """
    Per-test result entry in run_suite responses/progress (snake_case)
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    test_id: str
    flow_name: str
    status: str
    report_id: str | None = None
    message: str | None = None


class TriggerType(StrEnum):
    manual = 'manual'
    scheduled = 'scheduled'


class RunSuiteCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run_suite']
    """
    Command type
    """
    suite_id: str
    schedule_id: str | None = None
    trigger_type: TriggerType | None = None
    label: str | None = None
    run_config: SuiteRunConfigWire | None = None
    parallel: bool | None = None
    maxParallel: int | None = None
    stopOnFailure: bool | None = None


class CancelSuiteCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['cancel_suite']
    """
    Command type
    """
    suite_id: str
    running_test_ids: list[str]


class WaitType(StrEnum):
    duration = 'duration'
    element = 'element'
    interactable = 'interactable'


class AddRecordingWaitCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['add_recording_wait']
    """
    Command type
    """
    session_id: str
    wait_type: WaitType
    duration: float | None = None
    """
    ms; default 3000, min 100
    """
    timeout: float | None = None
    """
    ms; default 10000
    """
    selector: str | None = None
    """
    Required when wait_type is element or interactable
    """
    fallback_to_duration: bool | None = True
    fallback_duration: float | None = None
    """
    ms; default 2000
    """


class AuthenticateCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['authenticate']
    """
    Command type
    """
    token: str
    account_id: str | None = None
    """
    Sent by the client but not consumed by the engine (account derived from token)
    """
    server_url: str | None = None


class Status(StrEnum):
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'


class RunSuiteResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run_suite']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    suite_id: str | None = None
    suite_execution_id: str | None = None
    status: Status | None = None
    total: int | None = None
    completed: int | None = None
    passed: int | None = None
    failed: int | None = None
    cancelled: int | None = None
    test_results: list[SuiteTestResultWire] | None = None
    message: str | None = None
    """
    Response message
    """
    code: str | None = None
    error: str | None = None


class CancelSuiteResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['cancel_suite']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    suite_id: str
    signalled: bool


class AddRecordingWaitResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['add_recording_wait']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    session_id: str
    wait_action: dict[str, Any] | None = None
    message: str | None = None
    """
    Response message
    """
    error: str | None = None


class Code(StrEnum):
    ENGINE_TOKEN_MISSING = 'ENGINE_TOKEN_MISSING'
    ENGINE_TOKEN_INVALID = 'ENGINE_TOKEN_INVALID'
    ENGINE_CONNECTION_REFUSED = 'ENGINE_CONNECTION_REFUSED'
    ENGINE_AUTH_FAILED = 'ENGINE_AUTH_FAILED'
    ENGINE_ACCOUNT_CONFLICT = 'ENGINE_ACCOUNT_CONFLICT'


class AuthenticateResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['authenticate']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    account_id: str | None = None
    message: str | None = None
    """
    Response message
    """
    code: Code | None = None


class Runtime(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    is_docker: bool | None = None
    platform: str | None = None


class ConnectedResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['connected']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    host: str
    ws_port: int
    http_port: int
    runtime: Runtime


class RunSuiteProgressResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run_suite_progress']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    suite_id: str
    suite_execution_id: str
    status: Literal['running']
    total: int
    completed: int
    passed: int
    failed: int
    cancelled: int
    running: list[str]
    current: SuiteTestResultWire | None = None


class Data(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    waitActionId: str
    triggerActionId: str
    dependentActionId: str
    dependentActionType: str
    reason: str
    confidence: float | None
    waitType: str
    duration: int
    effectiveWaitMs: int
    selector: str
    selectors: list[str]


class RecordingSmartWaitDecision(BaseModel):
    """
    engine->frontend diagnostic emitted when a smart wait is inserted during recording. Top-level is snake_case; the data sub-object is camelCase (exception to the wire convention).
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    event: Literal['recording_smart_wait_decision']
    command: Literal['recording_smart_wait_decision']
    action_type: Literal['smart_wait_decision']
    timestamp: int
    """
    epoch ms
    """
    session_id: str
    flow_id: str
    data: Data


class ErrorResponse(WebSocketResponse):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: str
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    message: str
    """
    Response message
    """
    error: str


class ProcessKind(StrEnum):
    """
    The kind of engine work a process represents.
    """

    run = 'run'
    suite = 'suite'
    recording = 'recording'
    download = 'download'


class ProcessStatus(StrEnum):
    """
    Lifecycle state of a process. finished/completed/failed/cancelled/stopped are terminal. completed is used by download processes; other kinds use finished.
    """

    started = 'started'
    running = 'running'
    finished = 'finished'
    completed = 'completed'
    failed = 'failed'
    cancelled = 'cancelled'
    stopped = 'stopped'


class ProcessActionStatuses1(StrEnum):
    running = 'running'
    success = 'success'
    error = 'error'


class ProcessActionStatuses(RootModel[dict[str, ProcessActionStatuses1]]):
    """
    Per-action progress within a process, keyed by node id. Events carry only the actions that changed, so receivers merge rather than replace.
    """

    root: dict[str, ProcessActionStatuses1]


class Phase(StrEnum):
    """
    Download processes only: stage of the download.
    """

    downloading = 'downloading'
    extracting = 'extracting'
    verifying = 'verifying'


class ProcessEventResponse(WebSocketResponse):
    """
    Account-wide process lifecycle event. Broadcast to every live socket of an account so any client can bind a process to the test it belongs to and learn the outcome even if it did not start the work or has since reloaded.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['process_event']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    process_id: str
    """
    Stable id of the process for its lifetime.
    """
    kind: ProcessKind
    status: ProcessStatus
    test_id: str | None = None
    """
    Test this process belongs to, so clients gate only that test's controls.
    """
    initiated_by: str | None = None
    """
    User id that started the work, or the API key id for a CI run.
    """
    terminal: bool
    """
    True when the process has reached a final state.
    """
    mode: str | None = None
    report_id: str | None = None
    result: str | None = None
    message: str | None = None
    """
    Response message
    """
    actions: ProcessActionStatuses | None = None
    artifact: str | None = None
    """
    Download processes only: id of the downloaded artifact, e.g. "chrome" or "chromedriver".
    """
    label: str | None = None
    """
    Download processes only: human-readable name of the artifact, e.g. "Google Chrome".
    """
    phase: Phase | None = None
    """
    Download processes only: stage of the download.
    """
    bytes_downloaded: int | None = None
    """
    Download processes only: bytes transferred so far.
    """
    bytes_total: int | None = None
    """
    Download processes only: total bytes if the server reported Content-Length, else null.
    """
    percent: float | None = None
    """
    Download processes only: bytes_downloaded / bytes_total * 100, or null when bytes_total is unknown.
    """


class RunCommand(WebSocketMessage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['run']
    """
    Command type
    """
    browserAdapter: BrowserAdapter | None = None
    """
    Browser automation adapter for web actions; omitted uses the engine default. NOTE: this schema's RunCommand is a documentation model only — the real wire contract is the hand-maintained RunCommand in backend/engine/types/websocket_models.py, which must be edited to match.
    """
    flow: Flow
    """
    Flow to execute
    """
    mode: Mode | None = 'full'
    recording: dict[str, Any] | None = None
    mobile: MobileRunConfig | None = None
    """
    Appium session target for this run; required if the flow contains mobile* actions. NOTE: this schema's RunCommand is a documentation model only — the real wire contract is the hand-maintained RunCommand in backend/engine/types/websocket_models.py, which must be edited to match.
    """


class ProcessSnapshotResponse(WebSocketResponse):
    """
    The engine's full view of an account's processes, sent on every successful authenticate. This is how a reconnecting or reloaded client recovers work that started while it was away, including how far each run had progressed.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    command: Literal['process_snapshot']
    """
    Command that was executed
    """
    success: bool
    """
    Whether the command succeeded
    """
    processes: list[ProcessEventResponse]
    """
    Every process the engine still retains for the account. A process absent from this list is finished and forgotten.
    """


class WebsocketCommunication(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    commands: (
        list[
            RunCommand
            | RecordCommand
            | PauseRecordingCommand
            | ResumeRecordingCommand
            | StopRecordingCommand
            | FinishRecordingCommand
            | GetRecordingStatusCommand
            | ListRecordingsCommand
            | ConvertRecordingToFlowCommand
            | GetRealtimeActionsCommand
            | GetLatestRealtimeActionCommand
            | StopCommand
            | CloseCommand
            | ListSessionsCommand
            | CloseSessionCommand
            | RestartEngineCommand
            | CloseEngineCommand
            | GetEngineStatusCommand
            | StartPerformanceScanCommand
            | StopPerformanceScanCommand
            | RunLoadTestCommand
            | StopLoadTestCommand
            | DebugRunCommand
            | DebugStepCommand
            | DebugContinueCommand
            | DebugPauseCommand
            | DebugStopCommand
            | RunSuiteCommand
            | CancelSuiteCommand
            | AddRecordingWaitCommand
            | AuthenticateCommand
            | GetComponentsStatusCommand
            | InstallComponentCommand
            | RemoveComponentCommand
            | EnableSafaridriverCommand
        ]
        | None
    ) = None
    responses: (
        list[
            RunResponse
            | ListSessionsResponse
            | EngineStatusResponse
            | RecordingResponse
            | RecordingStatusResponse
            | ListRecordingsResponse
            | DebugResponse
            | WebSocketResponse
            | RunSuiteResponse
            | CancelSuiteResponse
            | AddRecordingWaitResponse
            | AuthenticateResponse
            | ConnectedResponse
            | RunSuiteProgressResponse
            | RecordingSmartWaitDecision
            | ErrorResponse
            | ProcessEventResponse
            | ProcessSnapshotResponse
        ]
        | None
    ) = None


class WebSocketCommunicationModels(BaseModel):
    """
    Schema for WebSocket API commands and responses
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    websocketCommunication: WebsocketCommunication | None = None
